// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: zsnd_news.proto

package com.mobile.api.proto;

public final class MAppNews {
  private MAppNews() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface MNewsListOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // repeated .com.mobile.api.proto.MNews news = 1;
    java.util.List<com.mobile.api.proto.MAppNews.MNews> 
        getNewsList();
    com.mobile.api.proto.MAppNews.MNews getNews(int index);
    int getNewsCount();
    java.util.List<? extends com.mobile.api.proto.MAppNews.MNewsOrBuilder> 
        getNewsOrBuilderList();
    com.mobile.api.proto.MAppNews.MNewsOrBuilder getNewsOrBuilder(
        int index);
    
    // optional string next = 2;
    boolean hasNext();
    String getNext();
  }
  public static final class MNewsList extends
      com.google.protobuf.GeneratedMessage
      implements MNewsListOrBuilder {
    // Use MNewsList.newBuilder() to construct.
    private MNewsList(Builder builder) {
      super(builder);
    }
    private MNewsList(boolean noInit) {}
    
    private static final MNewsList defaultInstance;
    public static MNewsList getDefaultInstance() {
      return defaultInstance;
    }
    
    public MNewsList getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.mobile.api.proto.MAppNews.internal_static_com_mobile_api_proto_MNewsList_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.mobile.api.proto.MAppNews.internal_static_com_mobile_api_proto_MNewsList_fieldAccessorTable;
    }
    
    private int bitField0_;
    // repeated .com.mobile.api.proto.MNews news = 1;
    public static final int NEWS_FIELD_NUMBER = 1;
    private java.util.List<com.mobile.api.proto.MAppNews.MNews> news_;
    public java.util.List<com.mobile.api.proto.MAppNews.MNews> getNewsList() {
      return news_;
    }
    public java.util.List<? extends com.mobile.api.proto.MAppNews.MNewsOrBuilder> 
        getNewsOrBuilderList() {
      return news_;
    }
    public int getNewsCount() {
      return news_.size();
    }
    public com.mobile.api.proto.MAppNews.MNews getNews(int index) {
      return news_.get(index);
    }
    public com.mobile.api.proto.MAppNews.MNewsOrBuilder getNewsOrBuilder(
        int index) {
      return news_.get(index);
    }
    
    // optional string next = 2;
    public static final int NEXT_FIELD_NUMBER = 2;
    private java.lang.Object next_;
    public boolean hasNext() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getNext() {
      java.lang.Object ref = next_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          next_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getNextBytes() {
      java.lang.Object ref = next_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        next_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    private void initFields() {
      news_ = java.util.Collections.emptyList();
      next_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < news_.size(); i++) {
        output.writeMessage(1, news_.get(i));
      }
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(2, getNextBytes());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      for (int i = 0; i < news_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, news_.get(i));
      }
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getNextBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.mobile.api.proto.MAppNews.MNewsList parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.mobile.api.proto.MAppNews.MNewsList parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.mobile.api.proto.MAppNews.MNewsList parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.mobile.api.proto.MAppNews.MNewsList parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.mobile.api.proto.MAppNews.MNewsList parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.mobile.api.proto.MAppNews.MNewsList parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.mobile.api.proto.MAppNews.MNewsList parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.mobile.api.proto.MAppNews.MNewsList parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.mobile.api.proto.MAppNews.MNewsList parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.mobile.api.proto.MAppNews.MNewsList parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.mobile.api.proto.MAppNews.MNewsList prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.mobile.api.proto.MAppNews.MNewsListOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.mobile.api.proto.MAppNews.internal_static_com_mobile_api_proto_MNewsList_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.mobile.api.proto.MAppNews.internal_static_com_mobile_api_proto_MNewsList_fieldAccessorTable;
      }
      
      // Construct using com.mobile.api.proto.MAppNews.MNewsList.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getNewsFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        if (newsBuilder_ == null) {
          news_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          newsBuilder_.clear();
        }
        next_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.mobile.api.proto.MAppNews.MNewsList.getDescriptor();
      }
      
      public com.mobile.api.proto.MAppNews.MNewsList getDefaultInstanceForType() {
        return com.mobile.api.proto.MAppNews.MNewsList.getDefaultInstance();
      }
      
      public com.mobile.api.proto.MAppNews.MNewsList build() {
        com.mobile.api.proto.MAppNews.MNewsList result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.mobile.api.proto.MAppNews.MNewsList buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.mobile.api.proto.MAppNews.MNewsList result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.mobile.api.proto.MAppNews.MNewsList buildPartial() {
        com.mobile.api.proto.MAppNews.MNewsList result = new com.mobile.api.proto.MAppNews.MNewsList(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (newsBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            news_ = java.util.Collections.unmodifiableList(news_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.news_ = news_;
        } else {
          result.news_ = newsBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000001;
        }
        result.next_ = next_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.mobile.api.proto.MAppNews.MNewsList) {
          return mergeFrom((com.mobile.api.proto.MAppNews.MNewsList)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.mobile.api.proto.MAppNews.MNewsList other) {
        if (other == com.mobile.api.proto.MAppNews.MNewsList.getDefaultInstance()) return this;
        if (newsBuilder_ == null) {
          if (!other.news_.isEmpty()) {
            if (news_.isEmpty()) {
              news_ = other.news_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureNewsIsMutable();
              news_.addAll(other.news_);
            }
            onChanged();
          }
        } else {
          if (!other.news_.isEmpty()) {
            if (newsBuilder_.isEmpty()) {
              newsBuilder_.dispose();
              newsBuilder_ = null;
              news_ = other.news_;
              bitField0_ = (bitField0_ & ~0x00000001);
              newsBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getNewsFieldBuilder() : null;
            } else {
              newsBuilder_.addAllMessages(other.news_);
            }
          }
        }
        if (other.hasNext()) {
          setNext(other.getNext());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              com.mobile.api.proto.MAppNews.MNews.Builder subBuilder = com.mobile.api.proto.MAppNews.MNews.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addNews(subBuilder.buildPartial());
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              next_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // repeated .com.mobile.api.proto.MNews news = 1;
      private java.util.List<com.mobile.api.proto.MAppNews.MNews> news_ =
        java.util.Collections.emptyList();
      private void ensureNewsIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          news_ = new java.util.ArrayList<com.mobile.api.proto.MAppNews.MNews>(news_);
          bitField0_ |= 0x00000001;
         }
      }
      
      private com.google.protobuf.RepeatedFieldBuilder<
          com.mobile.api.proto.MAppNews.MNews, com.mobile.api.proto.MAppNews.MNews.Builder, com.mobile.api.proto.MAppNews.MNewsOrBuilder> newsBuilder_;
      
      public java.util.List<com.mobile.api.proto.MAppNews.MNews> getNewsList() {
        if (newsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(news_);
        } else {
          return newsBuilder_.getMessageList();
        }
      }
      public int getNewsCount() {
        if (newsBuilder_ == null) {
          return news_.size();
        } else {
          return newsBuilder_.getCount();
        }
      }
      public com.mobile.api.proto.MAppNews.MNews getNews(int index) {
        if (newsBuilder_ == null) {
          return news_.get(index);
        } else {
          return newsBuilder_.getMessage(index);
        }
      }
      public Builder setNews(
          int index, com.mobile.api.proto.MAppNews.MNews value) {
        if (newsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureNewsIsMutable();
          news_.set(index, value);
          onChanged();
        } else {
          newsBuilder_.setMessage(index, value);
        }
        return this;
      }
      public Builder setNews(
          int index, com.mobile.api.proto.MAppNews.MNews.Builder builderForValue) {
        if (newsBuilder_ == null) {
          ensureNewsIsMutable();
          news_.set(index, builderForValue.build());
          onChanged();
        } else {
          newsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addNews(com.mobile.api.proto.MAppNews.MNews value) {
        if (newsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureNewsIsMutable();
          news_.add(value);
          onChanged();
        } else {
          newsBuilder_.addMessage(value);
        }
        return this;
      }
      public Builder addNews(
          int index, com.mobile.api.proto.MAppNews.MNews value) {
        if (newsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureNewsIsMutable();
          news_.add(index, value);
          onChanged();
        } else {
          newsBuilder_.addMessage(index, value);
        }
        return this;
      }
      public Builder addNews(
          com.mobile.api.proto.MAppNews.MNews.Builder builderForValue) {
        if (newsBuilder_ == null) {
          ensureNewsIsMutable();
          news_.add(builderForValue.build());
          onChanged();
        } else {
          newsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      public Builder addNews(
          int index, com.mobile.api.proto.MAppNews.MNews.Builder builderForValue) {
        if (newsBuilder_ == null) {
          ensureNewsIsMutable();
          news_.add(index, builderForValue.build());
          onChanged();
        } else {
          newsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAllNews(
          java.lang.Iterable<? extends com.mobile.api.proto.MAppNews.MNews> values) {
        if (newsBuilder_ == null) {
          ensureNewsIsMutable();
          super.addAll(values, news_);
          onChanged();
        } else {
          newsBuilder_.addAllMessages(values);
        }
        return this;
      }
      public Builder clearNews() {
        if (newsBuilder_ == null) {
          news_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          newsBuilder_.clear();
        }
        return this;
      }
      public Builder removeNews(int index) {
        if (newsBuilder_ == null) {
          ensureNewsIsMutable();
          news_.remove(index);
          onChanged();
        } else {
          newsBuilder_.remove(index);
        }
        return this;
      }
      public com.mobile.api.proto.MAppNews.MNews.Builder getNewsBuilder(
          int index) {
        return getNewsFieldBuilder().getBuilder(index);
      }
      public com.mobile.api.proto.MAppNews.MNewsOrBuilder getNewsOrBuilder(
          int index) {
        if (newsBuilder_ == null) {
          return news_.get(index);  } else {
          return newsBuilder_.getMessageOrBuilder(index);
        }
      }
      public java.util.List<? extends com.mobile.api.proto.MAppNews.MNewsOrBuilder> 
           getNewsOrBuilderList() {
        if (newsBuilder_ != null) {
          return newsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(news_);
        }
      }
      public com.mobile.api.proto.MAppNews.MNews.Builder addNewsBuilder() {
        return getNewsFieldBuilder().addBuilder(
            com.mobile.api.proto.MAppNews.MNews.getDefaultInstance());
      }
      public com.mobile.api.proto.MAppNews.MNews.Builder addNewsBuilder(
          int index) {
        return getNewsFieldBuilder().addBuilder(
            index, com.mobile.api.proto.MAppNews.MNews.getDefaultInstance());
      }
      public java.util.List<com.mobile.api.proto.MAppNews.MNews.Builder> 
           getNewsBuilderList() {
        return getNewsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.mobile.api.proto.MAppNews.MNews, com.mobile.api.proto.MAppNews.MNews.Builder, com.mobile.api.proto.MAppNews.MNewsOrBuilder> 
          getNewsFieldBuilder() {
        if (newsBuilder_ == null) {
          newsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.mobile.api.proto.MAppNews.MNews, com.mobile.api.proto.MAppNews.MNews.Builder, com.mobile.api.proto.MAppNews.MNewsOrBuilder>(
                  news_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          news_ = null;
        }
        return newsBuilder_;
      }
      
      // optional string next = 2;
      private java.lang.Object next_ = "";
      public boolean hasNext() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getNext() {
        java.lang.Object ref = next_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          next_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setNext(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        next_ = value;
        onChanged();
        return this;
      }
      public Builder clearNext() {
        bitField0_ = (bitField0_ & ~0x00000002);
        next_ = getDefaultInstance().getNext();
        onChanged();
        return this;
      }
      void setNext(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000002;
        next_ = value;
        onChanged();
      }
      
      // @@protoc_insertion_point(builder_scope:com.mobile.api.proto.MNewsList)
    }
    
    static {
      defaultInstance = new MNewsList(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.mobile.api.proto.MNewsList)
  }
  
  public interface MNewsOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // optional string id = 1;
    boolean hasId();
    String getId();
    
    // optional string img = 2;
    boolean hasImg();
    String getImg();
    
    // optional string noteId = 3;
    boolean hasNoteId();
    String getNoteId();
    
    // optional string title = 4;
    boolean hasTitle();
    String getTitle();
    
    // optional string desc = 5;
    boolean hasDesc();
    String getDesc();
    
    // optional string time = 6;
    boolean hasTime();
    String getTime();
    
    // optional string url = 7;
    boolean hasUrl();
    String getUrl();
    
    // optional int32 type = 8;
    boolean hasType();
    int getType();
    
    // optional string source = 9;
    boolean hasSource();
    String getSource();
    
    // optional int32 browseCount = 10;
    boolean hasBrowseCount();
    int getBrowseCount();
    
    // optional int32 praiseCount = 11;
    boolean hasPraiseCount();
    int getPraiseCount();
    
    // optional int32 commentCount = 12;
    boolean hasCommentCount();
    int getCommentCount();
    
    // optional int32 showType = 13;
    boolean hasShowType();
    int getShowType();
    
    // optional int32 isCollected = 14;
    boolean hasIsCollected();
    int getIsCollected();
    
    // optional int32 isPraised = 15;
    boolean hasIsPraised();
    int getIsPraised();
  }
  public static final class MNews extends
      com.google.protobuf.GeneratedMessage
      implements MNewsOrBuilder {
    // Use MNews.newBuilder() to construct.
    private MNews(Builder builder) {
      super(builder);
    }
    private MNews(boolean noInit) {}
    
    private static final MNews defaultInstance;
    public static MNews getDefaultInstance() {
      return defaultInstance;
    }
    
    public MNews getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.mobile.api.proto.MAppNews.internal_static_com_mobile_api_proto_MNews_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.mobile.api.proto.MAppNews.internal_static_com_mobile_api_proto_MNews_fieldAccessorTable;
    }
    
    private int bitField0_;
    // optional string id = 1;
    public static final int ID_FIELD_NUMBER = 1;
    private java.lang.Object id_;
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getId() {
      java.lang.Object ref = id_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          id_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string img = 2;
    public static final int IMG_FIELD_NUMBER = 2;
    private java.lang.Object img_;
    public boolean hasImg() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getImg() {
      java.lang.Object ref = img_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          img_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getImgBytes() {
      java.lang.Object ref = img_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        img_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string noteId = 3;
    public static final int NOTEID_FIELD_NUMBER = 3;
    private java.lang.Object noteId_;
    public boolean hasNoteId() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public String getNoteId() {
      java.lang.Object ref = noteId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          noteId_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getNoteIdBytes() {
      java.lang.Object ref = noteId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        noteId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string title = 4;
    public static final int TITLE_FIELD_NUMBER = 4;
    private java.lang.Object title_;
    public boolean hasTitle() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public String getTitle() {
      java.lang.Object ref = title_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          title_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getTitleBytes() {
      java.lang.Object ref = title_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        title_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string desc = 5;
    public static final int DESC_FIELD_NUMBER = 5;
    private java.lang.Object desc_;
    public boolean hasDesc() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    public String getDesc() {
      java.lang.Object ref = desc_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          desc_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getDescBytes() {
      java.lang.Object ref = desc_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        desc_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string time = 6;
    public static final int TIME_FIELD_NUMBER = 6;
    private java.lang.Object time_;
    public boolean hasTime() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    public String getTime() {
      java.lang.Object ref = time_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          time_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getTimeBytes() {
      java.lang.Object ref = time_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        time_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string url = 7;
    public static final int URL_FIELD_NUMBER = 7;
    private java.lang.Object url_;
    public boolean hasUrl() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    public String getUrl() {
      java.lang.Object ref = url_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          url_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getUrlBytes() {
      java.lang.Object ref = url_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        url_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional int32 type = 8;
    public static final int TYPE_FIELD_NUMBER = 8;
    private int type_;
    public boolean hasType() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    public int getType() {
      return type_;
    }
    
    // optional string source = 9;
    public static final int SOURCE_FIELD_NUMBER = 9;
    private java.lang.Object source_;
    public boolean hasSource() {
      return ((bitField0_ & 0x00000100) == 0x00000100);
    }
    public String getSource() {
      java.lang.Object ref = source_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          source_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getSourceBytes() {
      java.lang.Object ref = source_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        source_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional int32 browseCount = 10;
    public static final int BROWSECOUNT_FIELD_NUMBER = 10;
    private int browseCount_;
    public boolean hasBrowseCount() {
      return ((bitField0_ & 0x00000200) == 0x00000200);
    }
    public int getBrowseCount() {
      return browseCount_;
    }
    
    // optional int32 praiseCount = 11;
    public static final int PRAISECOUNT_FIELD_NUMBER = 11;
    private int praiseCount_;
    public boolean hasPraiseCount() {
      return ((bitField0_ & 0x00000400) == 0x00000400);
    }
    public int getPraiseCount() {
      return praiseCount_;
    }
    
    // optional int32 commentCount = 12;
    public static final int COMMENTCOUNT_FIELD_NUMBER = 12;
    private int commentCount_;
    public boolean hasCommentCount() {
      return ((bitField0_ & 0x00000800) == 0x00000800);
    }
    public int getCommentCount() {
      return commentCount_;
    }
    
    // optional int32 showType = 13;
    public static final int SHOWTYPE_FIELD_NUMBER = 13;
    private int showType_;
    public boolean hasShowType() {
      return ((bitField0_ & 0x00001000) == 0x00001000);
    }
    public int getShowType() {
      return showType_;
    }
    
    // optional int32 isCollected = 14;
    public static final int ISCOLLECTED_FIELD_NUMBER = 14;
    private int isCollected_;
    public boolean hasIsCollected() {
      return ((bitField0_ & 0x00002000) == 0x00002000);
    }
    public int getIsCollected() {
      return isCollected_;
    }
    
    // optional int32 isPraised = 15;
    public static final int ISPRAISED_FIELD_NUMBER = 15;
    private int isPraised_;
    public boolean hasIsPraised() {
      return ((bitField0_ & 0x00004000) == 0x00004000);
    }
    public int getIsPraised() {
      return isPraised_;
    }
    
    private void initFields() {
      id_ = "";
      img_ = "";
      noteId_ = "";
      title_ = "";
      desc_ = "";
      time_ = "";
      url_ = "";
      type_ = 0;
      source_ = "";
      browseCount_ = 0;
      praiseCount_ = 0;
      commentCount_ = 0;
      showType_ = 0;
      isCollected_ = 0;
      isPraised_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getImgBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getNoteIdBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getTitleBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(5, getDescBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeBytes(6, getTimeBytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeBytes(7, getUrlBytes());
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeInt32(8, type_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        output.writeBytes(9, getSourceBytes());
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        output.writeInt32(10, browseCount_);
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        output.writeInt32(11, praiseCount_);
      }
      if (((bitField0_ & 0x00000800) == 0x00000800)) {
        output.writeInt32(12, commentCount_);
      }
      if (((bitField0_ & 0x00001000) == 0x00001000)) {
        output.writeInt32(13, showType_);
      }
      if (((bitField0_ & 0x00002000) == 0x00002000)) {
        output.writeInt32(14, isCollected_);
      }
      if (((bitField0_ & 0x00004000) == 0x00004000)) {
        output.writeInt32(15, isPraised_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getImgBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getNoteIdBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getTitleBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, getDescBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, getTimeBytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(7, getUrlBytes());
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(8, type_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(9, getSourceBytes());
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(10, browseCount_);
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(11, praiseCount_);
      }
      if (((bitField0_ & 0x00000800) == 0x00000800)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(12, commentCount_);
      }
      if (((bitField0_ & 0x00001000) == 0x00001000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(13, showType_);
      }
      if (((bitField0_ & 0x00002000) == 0x00002000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(14, isCollected_);
      }
      if (((bitField0_ & 0x00004000) == 0x00004000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(15, isPraised_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.mobile.api.proto.MAppNews.MNews parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.mobile.api.proto.MAppNews.MNews parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.mobile.api.proto.MAppNews.MNews parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.mobile.api.proto.MAppNews.MNews parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.mobile.api.proto.MAppNews.MNews parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.mobile.api.proto.MAppNews.MNews parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.mobile.api.proto.MAppNews.MNews parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.mobile.api.proto.MAppNews.MNews parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.mobile.api.proto.MAppNews.MNews parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.mobile.api.proto.MAppNews.MNews parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.mobile.api.proto.MAppNews.MNews prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.mobile.api.proto.MAppNews.MNewsOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.mobile.api.proto.MAppNews.internal_static_com_mobile_api_proto_MNews_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.mobile.api.proto.MAppNews.internal_static_com_mobile_api_proto_MNews_fieldAccessorTable;
      }
      
      // Construct using com.mobile.api.proto.MAppNews.MNews.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        id_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        img_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        noteId_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        title_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        desc_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        time_ = "";
        bitField0_ = (bitField0_ & ~0x00000020);
        url_ = "";
        bitField0_ = (bitField0_ & ~0x00000040);
        type_ = 0;
        bitField0_ = (bitField0_ & ~0x00000080);
        source_ = "";
        bitField0_ = (bitField0_ & ~0x00000100);
        browseCount_ = 0;
        bitField0_ = (bitField0_ & ~0x00000200);
        praiseCount_ = 0;
        bitField0_ = (bitField0_ & ~0x00000400);
        commentCount_ = 0;
        bitField0_ = (bitField0_ & ~0x00000800);
        showType_ = 0;
        bitField0_ = (bitField0_ & ~0x00001000);
        isCollected_ = 0;
        bitField0_ = (bitField0_ & ~0x00002000);
        isPraised_ = 0;
        bitField0_ = (bitField0_ & ~0x00004000);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.mobile.api.proto.MAppNews.MNews.getDescriptor();
      }
      
      public com.mobile.api.proto.MAppNews.MNews getDefaultInstanceForType() {
        return com.mobile.api.proto.MAppNews.MNews.getDefaultInstance();
      }
      
      public com.mobile.api.proto.MAppNews.MNews build() {
        com.mobile.api.proto.MAppNews.MNews result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.mobile.api.proto.MAppNews.MNews buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.mobile.api.proto.MAppNews.MNews result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.mobile.api.proto.MAppNews.MNews buildPartial() {
        com.mobile.api.proto.MAppNews.MNews result = new com.mobile.api.proto.MAppNews.MNews(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.img_ = img_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.noteId_ = noteId_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.title_ = title_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.desc_ = desc_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.time_ = time_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.url_ = url_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.type_ = type_;
        if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
          to_bitField0_ |= 0x00000100;
        }
        result.source_ = source_;
        if (((from_bitField0_ & 0x00000200) == 0x00000200)) {
          to_bitField0_ |= 0x00000200;
        }
        result.browseCount_ = browseCount_;
        if (((from_bitField0_ & 0x00000400) == 0x00000400)) {
          to_bitField0_ |= 0x00000400;
        }
        result.praiseCount_ = praiseCount_;
        if (((from_bitField0_ & 0x00000800) == 0x00000800)) {
          to_bitField0_ |= 0x00000800;
        }
        result.commentCount_ = commentCount_;
        if (((from_bitField0_ & 0x00001000) == 0x00001000)) {
          to_bitField0_ |= 0x00001000;
        }
        result.showType_ = showType_;
        if (((from_bitField0_ & 0x00002000) == 0x00002000)) {
          to_bitField0_ |= 0x00002000;
        }
        result.isCollected_ = isCollected_;
        if (((from_bitField0_ & 0x00004000) == 0x00004000)) {
          to_bitField0_ |= 0x00004000;
        }
        result.isPraised_ = isPraised_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.mobile.api.proto.MAppNews.MNews) {
          return mergeFrom((com.mobile.api.proto.MAppNews.MNews)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.mobile.api.proto.MAppNews.MNews other) {
        if (other == com.mobile.api.proto.MAppNews.MNews.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasImg()) {
          setImg(other.getImg());
        }
        if (other.hasNoteId()) {
          setNoteId(other.getNoteId());
        }
        if (other.hasTitle()) {
          setTitle(other.getTitle());
        }
        if (other.hasDesc()) {
          setDesc(other.getDesc());
        }
        if (other.hasTime()) {
          setTime(other.getTime());
        }
        if (other.hasUrl()) {
          setUrl(other.getUrl());
        }
        if (other.hasType()) {
          setType(other.getType());
        }
        if (other.hasSource()) {
          setSource(other.getSource());
        }
        if (other.hasBrowseCount()) {
          setBrowseCount(other.getBrowseCount());
        }
        if (other.hasPraiseCount()) {
          setPraiseCount(other.getPraiseCount());
        }
        if (other.hasCommentCount()) {
          setCommentCount(other.getCommentCount());
        }
        if (other.hasShowType()) {
          setShowType(other.getShowType());
        }
        if (other.hasIsCollected()) {
          setIsCollected(other.getIsCollected());
        }
        if (other.hasIsPraised()) {
          setIsPraised(other.getIsPraised());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              id_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              img_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              noteId_ = input.readBytes();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              title_ = input.readBytes();
              break;
            }
            case 42: {
              bitField0_ |= 0x00000010;
              desc_ = input.readBytes();
              break;
            }
            case 50: {
              bitField0_ |= 0x00000020;
              time_ = input.readBytes();
              break;
            }
            case 58: {
              bitField0_ |= 0x00000040;
              url_ = input.readBytes();
              break;
            }
            case 64: {
              bitField0_ |= 0x00000080;
              type_ = input.readInt32();
              break;
            }
            case 74: {
              bitField0_ |= 0x00000100;
              source_ = input.readBytes();
              break;
            }
            case 80: {
              bitField0_ |= 0x00000200;
              browseCount_ = input.readInt32();
              break;
            }
            case 88: {
              bitField0_ |= 0x00000400;
              praiseCount_ = input.readInt32();
              break;
            }
            case 96: {
              bitField0_ |= 0x00000800;
              commentCount_ = input.readInt32();
              break;
            }
            case 104: {
              bitField0_ |= 0x00001000;
              showType_ = input.readInt32();
              break;
            }
            case 112: {
              bitField0_ |= 0x00002000;
              isCollected_ = input.readInt32();
              break;
            }
            case 120: {
              bitField0_ |= 0x00004000;
              isPraised_ = input.readInt32();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional string id = 1;
      private java.lang.Object id_ = "";
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getId() {
        java.lang.Object ref = id_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          id_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setId(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = getDefaultInstance().getId();
        onChanged();
        return this;
      }
      void setId(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
      }
      
      // optional string img = 2;
      private java.lang.Object img_ = "";
      public boolean hasImg() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getImg() {
        java.lang.Object ref = img_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          img_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setImg(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        img_ = value;
        onChanged();
        return this;
      }
      public Builder clearImg() {
        bitField0_ = (bitField0_ & ~0x00000002);
        img_ = getDefaultInstance().getImg();
        onChanged();
        return this;
      }
      void setImg(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000002;
        img_ = value;
        onChanged();
      }
      
      // optional string noteId = 3;
      private java.lang.Object noteId_ = "";
      public boolean hasNoteId() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public String getNoteId() {
        java.lang.Object ref = noteId_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          noteId_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setNoteId(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        noteId_ = value;
        onChanged();
        return this;
      }
      public Builder clearNoteId() {
        bitField0_ = (bitField0_ & ~0x00000004);
        noteId_ = getDefaultInstance().getNoteId();
        onChanged();
        return this;
      }
      void setNoteId(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000004;
        noteId_ = value;
        onChanged();
      }
      
      // optional string title = 4;
      private java.lang.Object title_ = "";
      public boolean hasTitle() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public String getTitle() {
        java.lang.Object ref = title_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          title_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setTitle(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        title_ = value;
        onChanged();
        return this;
      }
      public Builder clearTitle() {
        bitField0_ = (bitField0_ & ~0x00000008);
        title_ = getDefaultInstance().getTitle();
        onChanged();
        return this;
      }
      void setTitle(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000008;
        title_ = value;
        onChanged();
      }
      
      // optional string desc = 5;
      private java.lang.Object desc_ = "";
      public boolean hasDesc() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      public String getDesc() {
        java.lang.Object ref = desc_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          desc_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setDesc(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        desc_ = value;
        onChanged();
        return this;
      }
      public Builder clearDesc() {
        bitField0_ = (bitField0_ & ~0x00000010);
        desc_ = getDefaultInstance().getDesc();
        onChanged();
        return this;
      }
      void setDesc(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000010;
        desc_ = value;
        onChanged();
      }
      
      // optional string time = 6;
      private java.lang.Object time_ = "";
      public boolean hasTime() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      public String getTime() {
        java.lang.Object ref = time_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          time_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setTime(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        time_ = value;
        onChanged();
        return this;
      }
      public Builder clearTime() {
        bitField0_ = (bitField0_ & ~0x00000020);
        time_ = getDefaultInstance().getTime();
        onChanged();
        return this;
      }
      void setTime(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000020;
        time_ = value;
        onChanged();
      }
      
      // optional string url = 7;
      private java.lang.Object url_ = "";
      public boolean hasUrl() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      public String getUrl() {
        java.lang.Object ref = url_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          url_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setUrl(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        url_ = value;
        onChanged();
        return this;
      }
      public Builder clearUrl() {
        bitField0_ = (bitField0_ & ~0x00000040);
        url_ = getDefaultInstance().getUrl();
        onChanged();
        return this;
      }
      void setUrl(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000040;
        url_ = value;
        onChanged();
      }
      
      // optional int32 type = 8;
      private int type_ ;
      public boolean hasType() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      public int getType() {
        return type_;
      }
      public Builder setType(int value) {
        bitField0_ |= 0x00000080;
        type_ = value;
        onChanged();
        return this;
      }
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000080);
        type_ = 0;
        onChanged();
        return this;
      }
      
      // optional string source = 9;
      private java.lang.Object source_ = "";
      public boolean hasSource() {
        return ((bitField0_ & 0x00000100) == 0x00000100);
      }
      public String getSource() {
        java.lang.Object ref = source_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          source_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setSource(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000100;
        source_ = value;
        onChanged();
        return this;
      }
      public Builder clearSource() {
        bitField0_ = (bitField0_ & ~0x00000100);
        source_ = getDefaultInstance().getSource();
        onChanged();
        return this;
      }
      void setSource(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000100;
        source_ = value;
        onChanged();
      }
      
      // optional int32 browseCount = 10;
      private int browseCount_ ;
      public boolean hasBrowseCount() {
        return ((bitField0_ & 0x00000200) == 0x00000200);
      }
      public int getBrowseCount() {
        return browseCount_;
      }
      public Builder setBrowseCount(int value) {
        bitField0_ |= 0x00000200;
        browseCount_ = value;
        onChanged();
        return this;
      }
      public Builder clearBrowseCount() {
        bitField0_ = (bitField0_ & ~0x00000200);
        browseCount_ = 0;
        onChanged();
        return this;
      }
      
      // optional int32 praiseCount = 11;
      private int praiseCount_ ;
      public boolean hasPraiseCount() {
        return ((bitField0_ & 0x00000400) == 0x00000400);
      }
      public int getPraiseCount() {
        return praiseCount_;
      }
      public Builder setPraiseCount(int value) {
        bitField0_ |= 0x00000400;
        praiseCount_ = value;
        onChanged();
        return this;
      }
      public Builder clearPraiseCount() {
        bitField0_ = (bitField0_ & ~0x00000400);
        praiseCount_ = 0;
        onChanged();
        return this;
      }
      
      // optional int32 commentCount = 12;
      private int commentCount_ ;
      public boolean hasCommentCount() {
        return ((bitField0_ & 0x00000800) == 0x00000800);
      }
      public int getCommentCount() {
        return commentCount_;
      }
      public Builder setCommentCount(int value) {
        bitField0_ |= 0x00000800;
        commentCount_ = value;
        onChanged();
        return this;
      }
      public Builder clearCommentCount() {
        bitField0_ = (bitField0_ & ~0x00000800);
        commentCount_ = 0;
        onChanged();
        return this;
      }
      
      // optional int32 showType = 13;
      private int showType_ ;
      public boolean hasShowType() {
        return ((bitField0_ & 0x00001000) == 0x00001000);
      }
      public int getShowType() {
        return showType_;
      }
      public Builder setShowType(int value) {
        bitField0_ |= 0x00001000;
        showType_ = value;
        onChanged();
        return this;
      }
      public Builder clearShowType() {
        bitField0_ = (bitField0_ & ~0x00001000);
        showType_ = 0;
        onChanged();
        return this;
      }
      
      // optional int32 isCollected = 14;
      private int isCollected_ ;
      public boolean hasIsCollected() {
        return ((bitField0_ & 0x00002000) == 0x00002000);
      }
      public int getIsCollected() {
        return isCollected_;
      }
      public Builder setIsCollected(int value) {
        bitField0_ |= 0x00002000;
        isCollected_ = value;
        onChanged();
        return this;
      }
      public Builder clearIsCollected() {
        bitField0_ = (bitField0_ & ~0x00002000);
        isCollected_ = 0;
        onChanged();
        return this;
      }
      
      // optional int32 isPraised = 15;
      private int isPraised_ ;
      public boolean hasIsPraised() {
        return ((bitField0_ & 0x00004000) == 0x00004000);
      }
      public int getIsPraised() {
        return isPraised_;
      }
      public Builder setIsPraised(int value) {
        bitField0_ |= 0x00004000;
        isPraised_ = value;
        onChanged();
        return this;
      }
      public Builder clearIsPraised() {
        bitField0_ = (bitField0_ & ~0x00004000);
        isPraised_ = 0;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:com.mobile.api.proto.MNews)
    }
    
    static {
      defaultInstance = new MNews(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.mobile.api.proto.MNews)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_mobile_api_proto_MNewsList_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_mobile_api_proto_MNewsList_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_mobile_api_proto_MNews_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_mobile_api_proto_MNews_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017zsnd_news.proto\022\024com.mobile.api.proto\"" +
      "D\n\tMNewsList\022)\n\004news\030\001 \003(\0132\033.com.mobile." +
      "api.proto.MNews\022\014\n\004next\030\002 \001(\t\"\200\002\n\005MNews\022" +
      "\n\n\002id\030\001 \001(\t\022\013\n\003img\030\002 \001(\t\022\016\n\006noteId\030\003 \001(\t" +
      "\022\r\n\005title\030\004 \001(\t\022\014\n\004desc\030\005 \001(\t\022\014\n\004time\030\006 " +
      "\001(\t\022\013\n\003url\030\007 \001(\t\022\014\n\004type\030\010 \001(\005\022\016\n\006source" +
      "\030\t \001(\t\022\023\n\013browseCount\030\n \001(\005\022\023\n\013praiseCou" +
      "nt\030\013 \001(\005\022\024\n\014commentCount\030\014 \001(\005\022\020\n\010showTy" +
      "pe\030\r \001(\005\022\023\n\013isCollected\030\016 \001(\005\022\021\n\tisPrais" +
      "ed\030\017 \001(\005B\nB\010MAppNews"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_mobile_api_proto_MNewsList_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_mobile_api_proto_MNewsList_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_mobile_api_proto_MNewsList_descriptor,
              new java.lang.String[] { "News", "Next", },
              com.mobile.api.proto.MAppNews.MNewsList.class,
              com.mobile.api.proto.MAppNews.MNewsList.Builder.class);
          internal_static_com_mobile_api_proto_MNews_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_com_mobile_api_proto_MNews_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_mobile_api_proto_MNews_descriptor,
              new java.lang.String[] { "Id", "Img", "NoteId", "Title", "Desc", "Time", "Url", "Type", "Source", "BrowseCount", "PraiseCount", "CommentCount", "ShowType", "IsCollected", "IsPraised", },
              com.mobile.api.proto.MAppNews.MNews.class,
              com.mobile.api.proto.MAppNews.MNews.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
