// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: zsnd_library.proto

package com.mobile.api.proto;

public final class MAppLibrary {
  private MAppLibrary() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface MBookListOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // repeated .com.mobile.api.proto.MBook news = 1;
    java.util.List<com.mobile.api.proto.MAppLibrary.MBook> 
        getNewsList();
    com.mobile.api.proto.MAppLibrary.MBook getNews(int index);
    int getNewsCount();
    java.util.List<? extends com.mobile.api.proto.MAppLibrary.MBookOrBuilder> 
        getNewsOrBuilderList();
    com.mobile.api.proto.MAppLibrary.MBookOrBuilder getNewsOrBuilder(
        int index);
    
    // optional int32 cnt = 2;
    boolean hasCnt();
    int getCnt();
    
    // optional bytes img = 3;
    boolean hasImg();
    com.google.protobuf.ByteString getImg();
  }
  public static final class MBookList extends
      com.google.protobuf.GeneratedMessage
      implements MBookListOrBuilder {
    // Use MBookList.newBuilder() to construct.
    private MBookList(Builder builder) {
      super(builder);
    }
    private MBookList(boolean noInit) {}
    
    private static final MBookList defaultInstance;
    public static MBookList getDefaultInstance() {
      return defaultInstance;
    }
    
    public MBookList getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.mobile.api.proto.MAppLibrary.internal_static_com_mobile_api_proto_MBookList_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.mobile.api.proto.MAppLibrary.internal_static_com_mobile_api_proto_MBookList_fieldAccessorTable;
    }
    
    private int bitField0_;
    // repeated .com.mobile.api.proto.MBook news = 1;
    public static final int NEWS_FIELD_NUMBER = 1;
    private java.util.List<com.mobile.api.proto.MAppLibrary.MBook> news_;
    public java.util.List<com.mobile.api.proto.MAppLibrary.MBook> getNewsList() {
      return news_;
    }
    public java.util.List<? extends com.mobile.api.proto.MAppLibrary.MBookOrBuilder> 
        getNewsOrBuilderList() {
      return news_;
    }
    public int getNewsCount() {
      return news_.size();
    }
    public com.mobile.api.proto.MAppLibrary.MBook getNews(int index) {
      return news_.get(index);
    }
    public com.mobile.api.proto.MAppLibrary.MBookOrBuilder getNewsOrBuilder(
        int index) {
      return news_.get(index);
    }
    
    // optional int32 cnt = 2;
    public static final int CNT_FIELD_NUMBER = 2;
    private int cnt_;
    public boolean hasCnt() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public int getCnt() {
      return cnt_;
    }
    
    // optional bytes img = 3;
    public static final int IMG_FIELD_NUMBER = 3;
    private com.google.protobuf.ByteString img_;
    public boolean hasImg() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public com.google.protobuf.ByteString getImg() {
      return img_;
    }
    
    private void initFields() {
      news_ = java.util.Collections.emptyList();
      cnt_ = 0;
      img_ = com.google.protobuf.ByteString.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < news_.size(); i++) {
        output.writeMessage(1, news_.get(i));
      }
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(2, cnt_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(3, img_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      for (int i = 0; i < news_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, news_.get(i));
      }
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, cnt_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, img_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.mobile.api.proto.MAppLibrary.MBookList parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.mobile.api.proto.MAppLibrary.MBookList parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.mobile.api.proto.MAppLibrary.MBookList parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.mobile.api.proto.MAppLibrary.MBookList parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.mobile.api.proto.MAppLibrary.MBookList parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.mobile.api.proto.MAppLibrary.MBookList parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.mobile.api.proto.MAppLibrary.MBookList parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.mobile.api.proto.MAppLibrary.MBookList parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.mobile.api.proto.MAppLibrary.MBookList parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.mobile.api.proto.MAppLibrary.MBookList parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.mobile.api.proto.MAppLibrary.MBookList prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.mobile.api.proto.MAppLibrary.MBookListOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.mobile.api.proto.MAppLibrary.internal_static_com_mobile_api_proto_MBookList_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.mobile.api.proto.MAppLibrary.internal_static_com_mobile_api_proto_MBookList_fieldAccessorTable;
      }
      
      // Construct using com.mobile.api.proto.MAppLibrary.MBookList.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getNewsFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        if (newsBuilder_ == null) {
          news_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          newsBuilder_.clear();
        }
        cnt_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        img_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.mobile.api.proto.MAppLibrary.MBookList.getDescriptor();
      }
      
      public com.mobile.api.proto.MAppLibrary.MBookList getDefaultInstanceForType() {
        return com.mobile.api.proto.MAppLibrary.MBookList.getDefaultInstance();
      }
      
      public com.mobile.api.proto.MAppLibrary.MBookList build() {
        com.mobile.api.proto.MAppLibrary.MBookList result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.mobile.api.proto.MAppLibrary.MBookList buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.mobile.api.proto.MAppLibrary.MBookList result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.mobile.api.proto.MAppLibrary.MBookList buildPartial() {
        com.mobile.api.proto.MAppLibrary.MBookList result = new com.mobile.api.proto.MAppLibrary.MBookList(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (newsBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            news_ = java.util.Collections.unmodifiableList(news_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.news_ = news_;
        } else {
          result.news_ = newsBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000001;
        }
        result.cnt_ = cnt_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000002;
        }
        result.img_ = img_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.mobile.api.proto.MAppLibrary.MBookList) {
          return mergeFrom((com.mobile.api.proto.MAppLibrary.MBookList)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.mobile.api.proto.MAppLibrary.MBookList other) {
        if (other == com.mobile.api.proto.MAppLibrary.MBookList.getDefaultInstance()) return this;
        if (newsBuilder_ == null) {
          if (!other.news_.isEmpty()) {
            if (news_.isEmpty()) {
              news_ = other.news_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureNewsIsMutable();
              news_.addAll(other.news_);
            }
            onChanged();
          }
        } else {
          if (!other.news_.isEmpty()) {
            if (newsBuilder_.isEmpty()) {
              newsBuilder_.dispose();
              newsBuilder_ = null;
              news_ = other.news_;
              bitField0_ = (bitField0_ & ~0x00000001);
              newsBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getNewsFieldBuilder() : null;
            } else {
              newsBuilder_.addAllMessages(other.news_);
            }
          }
        }
        if (other.hasCnt()) {
          setCnt(other.getCnt());
        }
        if (other.hasImg()) {
          setImg(other.getImg());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              com.mobile.api.proto.MAppLibrary.MBook.Builder subBuilder = com.mobile.api.proto.MAppLibrary.MBook.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addNews(subBuilder.buildPartial());
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              cnt_ = input.readInt32();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              img_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // repeated .com.mobile.api.proto.MBook news = 1;
      private java.util.List<com.mobile.api.proto.MAppLibrary.MBook> news_ =
        java.util.Collections.emptyList();
      private void ensureNewsIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          news_ = new java.util.ArrayList<com.mobile.api.proto.MAppLibrary.MBook>(news_);
          bitField0_ |= 0x00000001;
         }
      }
      
      private com.google.protobuf.RepeatedFieldBuilder<
          com.mobile.api.proto.MAppLibrary.MBook, com.mobile.api.proto.MAppLibrary.MBook.Builder, com.mobile.api.proto.MAppLibrary.MBookOrBuilder> newsBuilder_;
      
      public java.util.List<com.mobile.api.proto.MAppLibrary.MBook> getNewsList() {
        if (newsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(news_);
        } else {
          return newsBuilder_.getMessageList();
        }
      }
      public int getNewsCount() {
        if (newsBuilder_ == null) {
          return news_.size();
        } else {
          return newsBuilder_.getCount();
        }
      }
      public com.mobile.api.proto.MAppLibrary.MBook getNews(int index) {
        if (newsBuilder_ == null) {
          return news_.get(index);
        } else {
          return newsBuilder_.getMessage(index);
        }
      }
      public Builder setNews(
          int index, com.mobile.api.proto.MAppLibrary.MBook value) {
        if (newsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureNewsIsMutable();
          news_.set(index, value);
          onChanged();
        } else {
          newsBuilder_.setMessage(index, value);
        }
        return this;
      }
      public Builder setNews(
          int index, com.mobile.api.proto.MAppLibrary.MBook.Builder builderForValue) {
        if (newsBuilder_ == null) {
          ensureNewsIsMutable();
          news_.set(index, builderForValue.build());
          onChanged();
        } else {
          newsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addNews(com.mobile.api.proto.MAppLibrary.MBook value) {
        if (newsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureNewsIsMutable();
          news_.add(value);
          onChanged();
        } else {
          newsBuilder_.addMessage(value);
        }
        return this;
      }
      public Builder addNews(
          int index, com.mobile.api.proto.MAppLibrary.MBook value) {
        if (newsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureNewsIsMutable();
          news_.add(index, value);
          onChanged();
        } else {
          newsBuilder_.addMessage(index, value);
        }
        return this;
      }
      public Builder addNews(
          com.mobile.api.proto.MAppLibrary.MBook.Builder builderForValue) {
        if (newsBuilder_ == null) {
          ensureNewsIsMutable();
          news_.add(builderForValue.build());
          onChanged();
        } else {
          newsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      public Builder addNews(
          int index, com.mobile.api.proto.MAppLibrary.MBook.Builder builderForValue) {
        if (newsBuilder_ == null) {
          ensureNewsIsMutable();
          news_.add(index, builderForValue.build());
          onChanged();
        } else {
          newsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAllNews(
          java.lang.Iterable<? extends com.mobile.api.proto.MAppLibrary.MBook> values) {
        if (newsBuilder_ == null) {
          ensureNewsIsMutable();
          super.addAll(values, news_);
          onChanged();
        } else {
          newsBuilder_.addAllMessages(values);
        }
        return this;
      }
      public Builder clearNews() {
        if (newsBuilder_ == null) {
          news_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          newsBuilder_.clear();
        }
        return this;
      }
      public Builder removeNews(int index) {
        if (newsBuilder_ == null) {
          ensureNewsIsMutable();
          news_.remove(index);
          onChanged();
        } else {
          newsBuilder_.remove(index);
        }
        return this;
      }
      public com.mobile.api.proto.MAppLibrary.MBook.Builder getNewsBuilder(
          int index) {
        return getNewsFieldBuilder().getBuilder(index);
      }
      public com.mobile.api.proto.MAppLibrary.MBookOrBuilder getNewsOrBuilder(
          int index) {
        if (newsBuilder_ == null) {
          return news_.get(index);  } else {
          return newsBuilder_.getMessageOrBuilder(index);
        }
      }
      public java.util.List<? extends com.mobile.api.proto.MAppLibrary.MBookOrBuilder> 
           getNewsOrBuilderList() {
        if (newsBuilder_ != null) {
          return newsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(news_);
        }
      }
      public com.mobile.api.proto.MAppLibrary.MBook.Builder addNewsBuilder() {
        return getNewsFieldBuilder().addBuilder(
            com.mobile.api.proto.MAppLibrary.MBook.getDefaultInstance());
      }
      public com.mobile.api.proto.MAppLibrary.MBook.Builder addNewsBuilder(
          int index) {
        return getNewsFieldBuilder().addBuilder(
            index, com.mobile.api.proto.MAppLibrary.MBook.getDefaultInstance());
      }
      public java.util.List<com.mobile.api.proto.MAppLibrary.MBook.Builder> 
           getNewsBuilderList() {
        return getNewsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.mobile.api.proto.MAppLibrary.MBook, com.mobile.api.proto.MAppLibrary.MBook.Builder, com.mobile.api.proto.MAppLibrary.MBookOrBuilder> 
          getNewsFieldBuilder() {
        if (newsBuilder_ == null) {
          newsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.mobile.api.proto.MAppLibrary.MBook, com.mobile.api.proto.MAppLibrary.MBook.Builder, com.mobile.api.proto.MAppLibrary.MBookOrBuilder>(
                  news_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          news_ = null;
        }
        return newsBuilder_;
      }
      
      // optional int32 cnt = 2;
      private int cnt_ ;
      public boolean hasCnt() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public int getCnt() {
        return cnt_;
      }
      public Builder setCnt(int value) {
        bitField0_ |= 0x00000002;
        cnt_ = value;
        onChanged();
        return this;
      }
      public Builder clearCnt() {
        bitField0_ = (bitField0_ & ~0x00000002);
        cnt_ = 0;
        onChanged();
        return this;
      }
      
      // optional bytes img = 3;
      private com.google.protobuf.ByteString img_ = com.google.protobuf.ByteString.EMPTY;
      public boolean hasImg() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public com.google.protobuf.ByteString getImg() {
        return img_;
      }
      public Builder setImg(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        img_ = value;
        onChanged();
        return this;
      }
      public Builder clearImg() {
        bitField0_ = (bitField0_ & ~0x00000004);
        img_ = getDefaultInstance().getImg();
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:com.mobile.api.proto.MBookList)
    }
    
    static {
      defaultInstance = new MBookList(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.mobile.api.proto.MBookList)
  }
  
  public interface MBookOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // optional string id = 1;
    boolean hasId();
    String getId();
    
    // optional string title = 2;
    boolean hasTitle();
    String getTitle();
    
    // optional string author = 3;
    boolean hasAuthor();
    String getAuthor();
    
    // optional string publish = 4;
    boolean hasPublish();
    String getPublish();
    
    // optional int32 total = 5;
    boolean hasTotal();
    int getTotal();
    
    // optional int32 canBorrow = 6;
    boolean hasCanBorrow();
    int getCanBorrow();
    
    // optional string borrowTime = 7;
    boolean hasBorrowTime();
    String getBorrowTime();
    
    // optional string backTime = 8;
    boolean hasBackTime();
    String getBackTime();
    
    // optional int32 canRenew = 9;
    boolean hasCanRenew();
    int getCanRenew();
    
    // repeated .com.mobile.api.proto.MBookDetail details = 10;
    java.util.List<com.mobile.api.proto.MAppLibrary.MBookDetail> 
        getDetailsList();
    com.mobile.api.proto.MAppLibrary.MBookDetail getDetails(int index);
    int getDetailsCount();
    java.util.List<? extends com.mobile.api.proto.MAppLibrary.MBookDetailOrBuilder> 
        getDetailsOrBuilderList();
    com.mobile.api.proto.MAppLibrary.MBookDetailOrBuilder getDetailsOrBuilder(
        int index);
  }
  public static final class MBook extends
      com.google.protobuf.GeneratedMessage
      implements MBookOrBuilder {
    // Use MBook.newBuilder() to construct.
    private MBook(Builder builder) {
      super(builder);
    }
    private MBook(boolean noInit) {}
    
    private static final MBook defaultInstance;
    public static MBook getDefaultInstance() {
      return defaultInstance;
    }
    
    public MBook getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.mobile.api.proto.MAppLibrary.internal_static_com_mobile_api_proto_MBook_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.mobile.api.proto.MAppLibrary.internal_static_com_mobile_api_proto_MBook_fieldAccessorTable;
    }
    
    private int bitField0_;
    // optional string id = 1;
    public static final int ID_FIELD_NUMBER = 1;
    private java.lang.Object id_;
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getId() {
      java.lang.Object ref = id_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          id_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string title = 2;
    public static final int TITLE_FIELD_NUMBER = 2;
    private java.lang.Object title_;
    public boolean hasTitle() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getTitle() {
      java.lang.Object ref = title_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          title_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getTitleBytes() {
      java.lang.Object ref = title_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        title_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string author = 3;
    public static final int AUTHOR_FIELD_NUMBER = 3;
    private java.lang.Object author_;
    public boolean hasAuthor() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public String getAuthor() {
      java.lang.Object ref = author_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          author_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getAuthorBytes() {
      java.lang.Object ref = author_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        author_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string publish = 4;
    public static final int PUBLISH_FIELD_NUMBER = 4;
    private java.lang.Object publish_;
    public boolean hasPublish() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public String getPublish() {
      java.lang.Object ref = publish_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          publish_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getPublishBytes() {
      java.lang.Object ref = publish_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        publish_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional int32 total = 5;
    public static final int TOTAL_FIELD_NUMBER = 5;
    private int total_;
    public boolean hasTotal() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    public int getTotal() {
      return total_;
    }
    
    // optional int32 canBorrow = 6;
    public static final int CANBORROW_FIELD_NUMBER = 6;
    private int canBorrow_;
    public boolean hasCanBorrow() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    public int getCanBorrow() {
      return canBorrow_;
    }
    
    // optional string borrowTime = 7;
    public static final int BORROWTIME_FIELD_NUMBER = 7;
    private java.lang.Object borrowTime_;
    public boolean hasBorrowTime() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    public String getBorrowTime() {
      java.lang.Object ref = borrowTime_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          borrowTime_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getBorrowTimeBytes() {
      java.lang.Object ref = borrowTime_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        borrowTime_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string backTime = 8;
    public static final int BACKTIME_FIELD_NUMBER = 8;
    private java.lang.Object backTime_;
    public boolean hasBackTime() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    public String getBackTime() {
      java.lang.Object ref = backTime_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          backTime_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getBackTimeBytes() {
      java.lang.Object ref = backTime_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        backTime_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional int32 canRenew = 9;
    public static final int CANRENEW_FIELD_NUMBER = 9;
    private int canRenew_;
    public boolean hasCanRenew() {
      return ((bitField0_ & 0x00000100) == 0x00000100);
    }
    public int getCanRenew() {
      return canRenew_;
    }
    
    // repeated .com.mobile.api.proto.MBookDetail details = 10;
    public static final int DETAILS_FIELD_NUMBER = 10;
    private java.util.List<com.mobile.api.proto.MAppLibrary.MBookDetail> details_;
    public java.util.List<com.mobile.api.proto.MAppLibrary.MBookDetail> getDetailsList() {
      return details_;
    }
    public java.util.List<? extends com.mobile.api.proto.MAppLibrary.MBookDetailOrBuilder> 
        getDetailsOrBuilderList() {
      return details_;
    }
    public int getDetailsCount() {
      return details_.size();
    }
    public com.mobile.api.proto.MAppLibrary.MBookDetail getDetails(int index) {
      return details_.get(index);
    }
    public com.mobile.api.proto.MAppLibrary.MBookDetailOrBuilder getDetailsOrBuilder(
        int index) {
      return details_.get(index);
    }
    
    private void initFields() {
      id_ = "";
      title_ = "";
      author_ = "";
      publish_ = "";
      total_ = 0;
      canBorrow_ = 0;
      borrowTime_ = "";
      backTime_ = "";
      canRenew_ = 0;
      details_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getTitleBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getAuthorBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getPublishBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt32(5, total_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeInt32(6, canBorrow_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeBytes(7, getBorrowTimeBytes());
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeBytes(8, getBackTimeBytes());
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        output.writeInt32(9, canRenew_);
      }
      for (int i = 0; i < details_.size(); i++) {
        output.writeMessage(10, details_.get(i));
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getTitleBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getAuthorBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getPublishBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, total_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, canBorrow_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(7, getBorrowTimeBytes());
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(8, getBackTimeBytes());
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(9, canRenew_);
      }
      for (int i = 0; i < details_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(10, details_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.mobile.api.proto.MAppLibrary.MBook parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.mobile.api.proto.MAppLibrary.MBook parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.mobile.api.proto.MAppLibrary.MBook parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.mobile.api.proto.MAppLibrary.MBook parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.mobile.api.proto.MAppLibrary.MBook parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.mobile.api.proto.MAppLibrary.MBook parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.mobile.api.proto.MAppLibrary.MBook parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.mobile.api.proto.MAppLibrary.MBook parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.mobile.api.proto.MAppLibrary.MBook parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.mobile.api.proto.MAppLibrary.MBook parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.mobile.api.proto.MAppLibrary.MBook prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.mobile.api.proto.MAppLibrary.MBookOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.mobile.api.proto.MAppLibrary.internal_static_com_mobile_api_proto_MBook_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.mobile.api.proto.MAppLibrary.internal_static_com_mobile_api_proto_MBook_fieldAccessorTable;
      }
      
      // Construct using com.mobile.api.proto.MAppLibrary.MBook.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getDetailsFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        id_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        title_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        author_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        publish_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        total_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        canBorrow_ = 0;
        bitField0_ = (bitField0_ & ~0x00000020);
        borrowTime_ = "";
        bitField0_ = (bitField0_ & ~0x00000040);
        backTime_ = "";
        bitField0_ = (bitField0_ & ~0x00000080);
        canRenew_ = 0;
        bitField0_ = (bitField0_ & ~0x00000100);
        if (detailsBuilder_ == null) {
          details_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000200);
        } else {
          detailsBuilder_.clear();
        }
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.mobile.api.proto.MAppLibrary.MBook.getDescriptor();
      }
      
      public com.mobile.api.proto.MAppLibrary.MBook getDefaultInstanceForType() {
        return com.mobile.api.proto.MAppLibrary.MBook.getDefaultInstance();
      }
      
      public com.mobile.api.proto.MAppLibrary.MBook build() {
        com.mobile.api.proto.MAppLibrary.MBook result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.mobile.api.proto.MAppLibrary.MBook buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.mobile.api.proto.MAppLibrary.MBook result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.mobile.api.proto.MAppLibrary.MBook buildPartial() {
        com.mobile.api.proto.MAppLibrary.MBook result = new com.mobile.api.proto.MAppLibrary.MBook(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.title_ = title_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.author_ = author_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.publish_ = publish_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.total_ = total_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.canBorrow_ = canBorrow_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.borrowTime_ = borrowTime_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.backTime_ = backTime_;
        if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
          to_bitField0_ |= 0x00000100;
        }
        result.canRenew_ = canRenew_;
        if (detailsBuilder_ == null) {
          if (((bitField0_ & 0x00000200) == 0x00000200)) {
            details_ = java.util.Collections.unmodifiableList(details_);
            bitField0_ = (bitField0_ & ~0x00000200);
          }
          result.details_ = details_;
        } else {
          result.details_ = detailsBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.mobile.api.proto.MAppLibrary.MBook) {
          return mergeFrom((com.mobile.api.proto.MAppLibrary.MBook)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.mobile.api.proto.MAppLibrary.MBook other) {
        if (other == com.mobile.api.proto.MAppLibrary.MBook.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasTitle()) {
          setTitle(other.getTitle());
        }
        if (other.hasAuthor()) {
          setAuthor(other.getAuthor());
        }
        if (other.hasPublish()) {
          setPublish(other.getPublish());
        }
        if (other.hasTotal()) {
          setTotal(other.getTotal());
        }
        if (other.hasCanBorrow()) {
          setCanBorrow(other.getCanBorrow());
        }
        if (other.hasBorrowTime()) {
          setBorrowTime(other.getBorrowTime());
        }
        if (other.hasBackTime()) {
          setBackTime(other.getBackTime());
        }
        if (other.hasCanRenew()) {
          setCanRenew(other.getCanRenew());
        }
        if (detailsBuilder_ == null) {
          if (!other.details_.isEmpty()) {
            if (details_.isEmpty()) {
              details_ = other.details_;
              bitField0_ = (bitField0_ & ~0x00000200);
            } else {
              ensureDetailsIsMutable();
              details_.addAll(other.details_);
            }
            onChanged();
          }
        } else {
          if (!other.details_.isEmpty()) {
            if (detailsBuilder_.isEmpty()) {
              detailsBuilder_.dispose();
              detailsBuilder_ = null;
              details_ = other.details_;
              bitField0_ = (bitField0_ & ~0x00000200);
              detailsBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getDetailsFieldBuilder() : null;
            } else {
              detailsBuilder_.addAllMessages(other.details_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              id_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              title_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              author_ = input.readBytes();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              publish_ = input.readBytes();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              total_ = input.readInt32();
              break;
            }
            case 48: {
              bitField0_ |= 0x00000020;
              canBorrow_ = input.readInt32();
              break;
            }
            case 58: {
              bitField0_ |= 0x00000040;
              borrowTime_ = input.readBytes();
              break;
            }
            case 66: {
              bitField0_ |= 0x00000080;
              backTime_ = input.readBytes();
              break;
            }
            case 72: {
              bitField0_ |= 0x00000100;
              canRenew_ = input.readInt32();
              break;
            }
            case 82: {
              com.mobile.api.proto.MAppLibrary.MBookDetail.Builder subBuilder = com.mobile.api.proto.MAppLibrary.MBookDetail.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addDetails(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional string id = 1;
      private java.lang.Object id_ = "";
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getId() {
        java.lang.Object ref = id_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          id_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setId(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = getDefaultInstance().getId();
        onChanged();
        return this;
      }
      void setId(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
      }
      
      // optional string title = 2;
      private java.lang.Object title_ = "";
      public boolean hasTitle() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getTitle() {
        java.lang.Object ref = title_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          title_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setTitle(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        title_ = value;
        onChanged();
        return this;
      }
      public Builder clearTitle() {
        bitField0_ = (bitField0_ & ~0x00000002);
        title_ = getDefaultInstance().getTitle();
        onChanged();
        return this;
      }
      void setTitle(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000002;
        title_ = value;
        onChanged();
      }
      
      // optional string author = 3;
      private java.lang.Object author_ = "";
      public boolean hasAuthor() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public String getAuthor() {
        java.lang.Object ref = author_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          author_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setAuthor(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        author_ = value;
        onChanged();
        return this;
      }
      public Builder clearAuthor() {
        bitField0_ = (bitField0_ & ~0x00000004);
        author_ = getDefaultInstance().getAuthor();
        onChanged();
        return this;
      }
      void setAuthor(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000004;
        author_ = value;
        onChanged();
      }
      
      // optional string publish = 4;
      private java.lang.Object publish_ = "";
      public boolean hasPublish() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public String getPublish() {
        java.lang.Object ref = publish_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          publish_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setPublish(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        publish_ = value;
        onChanged();
        return this;
      }
      public Builder clearPublish() {
        bitField0_ = (bitField0_ & ~0x00000008);
        publish_ = getDefaultInstance().getPublish();
        onChanged();
        return this;
      }
      void setPublish(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000008;
        publish_ = value;
        onChanged();
      }
      
      // optional int32 total = 5;
      private int total_ ;
      public boolean hasTotal() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      public int getTotal() {
        return total_;
      }
      public Builder setTotal(int value) {
        bitField0_ |= 0x00000010;
        total_ = value;
        onChanged();
        return this;
      }
      public Builder clearTotal() {
        bitField0_ = (bitField0_ & ~0x00000010);
        total_ = 0;
        onChanged();
        return this;
      }
      
      // optional int32 canBorrow = 6;
      private int canBorrow_ ;
      public boolean hasCanBorrow() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      public int getCanBorrow() {
        return canBorrow_;
      }
      public Builder setCanBorrow(int value) {
        bitField0_ |= 0x00000020;
        canBorrow_ = value;
        onChanged();
        return this;
      }
      public Builder clearCanBorrow() {
        bitField0_ = (bitField0_ & ~0x00000020);
        canBorrow_ = 0;
        onChanged();
        return this;
      }
      
      // optional string borrowTime = 7;
      private java.lang.Object borrowTime_ = "";
      public boolean hasBorrowTime() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      public String getBorrowTime() {
        java.lang.Object ref = borrowTime_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          borrowTime_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setBorrowTime(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        borrowTime_ = value;
        onChanged();
        return this;
      }
      public Builder clearBorrowTime() {
        bitField0_ = (bitField0_ & ~0x00000040);
        borrowTime_ = getDefaultInstance().getBorrowTime();
        onChanged();
        return this;
      }
      void setBorrowTime(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000040;
        borrowTime_ = value;
        onChanged();
      }
      
      // optional string backTime = 8;
      private java.lang.Object backTime_ = "";
      public boolean hasBackTime() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      public String getBackTime() {
        java.lang.Object ref = backTime_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          backTime_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setBackTime(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
        backTime_ = value;
        onChanged();
        return this;
      }
      public Builder clearBackTime() {
        bitField0_ = (bitField0_ & ~0x00000080);
        backTime_ = getDefaultInstance().getBackTime();
        onChanged();
        return this;
      }
      void setBackTime(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000080;
        backTime_ = value;
        onChanged();
      }
      
      // optional int32 canRenew = 9;
      private int canRenew_ ;
      public boolean hasCanRenew() {
        return ((bitField0_ & 0x00000100) == 0x00000100);
      }
      public int getCanRenew() {
        return canRenew_;
      }
      public Builder setCanRenew(int value) {
        bitField0_ |= 0x00000100;
        canRenew_ = value;
        onChanged();
        return this;
      }
      public Builder clearCanRenew() {
        bitField0_ = (bitField0_ & ~0x00000100);
        canRenew_ = 0;
        onChanged();
        return this;
      }
      
      // repeated .com.mobile.api.proto.MBookDetail details = 10;
      private java.util.List<com.mobile.api.proto.MAppLibrary.MBookDetail> details_ =
        java.util.Collections.emptyList();
      private void ensureDetailsIsMutable() {
        if (!((bitField0_ & 0x00000200) == 0x00000200)) {
          details_ = new java.util.ArrayList<com.mobile.api.proto.MAppLibrary.MBookDetail>(details_);
          bitField0_ |= 0x00000200;
         }
      }
      
      private com.google.protobuf.RepeatedFieldBuilder<
          com.mobile.api.proto.MAppLibrary.MBookDetail, com.mobile.api.proto.MAppLibrary.MBookDetail.Builder, com.mobile.api.proto.MAppLibrary.MBookDetailOrBuilder> detailsBuilder_;
      
      public java.util.List<com.mobile.api.proto.MAppLibrary.MBookDetail> getDetailsList() {
        if (detailsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(details_);
        } else {
          return detailsBuilder_.getMessageList();
        }
      }
      public int getDetailsCount() {
        if (detailsBuilder_ == null) {
          return details_.size();
        } else {
          return detailsBuilder_.getCount();
        }
      }
      public com.mobile.api.proto.MAppLibrary.MBookDetail getDetails(int index) {
        if (detailsBuilder_ == null) {
          return details_.get(index);
        } else {
          return detailsBuilder_.getMessage(index);
        }
      }
      public Builder setDetails(
          int index, com.mobile.api.proto.MAppLibrary.MBookDetail value) {
        if (detailsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDetailsIsMutable();
          details_.set(index, value);
          onChanged();
        } else {
          detailsBuilder_.setMessage(index, value);
        }
        return this;
      }
      public Builder setDetails(
          int index, com.mobile.api.proto.MAppLibrary.MBookDetail.Builder builderForValue) {
        if (detailsBuilder_ == null) {
          ensureDetailsIsMutable();
          details_.set(index, builderForValue.build());
          onChanged();
        } else {
          detailsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addDetails(com.mobile.api.proto.MAppLibrary.MBookDetail value) {
        if (detailsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDetailsIsMutable();
          details_.add(value);
          onChanged();
        } else {
          detailsBuilder_.addMessage(value);
        }
        return this;
      }
      public Builder addDetails(
          int index, com.mobile.api.proto.MAppLibrary.MBookDetail value) {
        if (detailsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDetailsIsMutable();
          details_.add(index, value);
          onChanged();
        } else {
          detailsBuilder_.addMessage(index, value);
        }
        return this;
      }
      public Builder addDetails(
          com.mobile.api.proto.MAppLibrary.MBookDetail.Builder builderForValue) {
        if (detailsBuilder_ == null) {
          ensureDetailsIsMutable();
          details_.add(builderForValue.build());
          onChanged();
        } else {
          detailsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      public Builder addDetails(
          int index, com.mobile.api.proto.MAppLibrary.MBookDetail.Builder builderForValue) {
        if (detailsBuilder_ == null) {
          ensureDetailsIsMutable();
          details_.add(index, builderForValue.build());
          onChanged();
        } else {
          detailsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAllDetails(
          java.lang.Iterable<? extends com.mobile.api.proto.MAppLibrary.MBookDetail> values) {
        if (detailsBuilder_ == null) {
          ensureDetailsIsMutable();
          super.addAll(values, details_);
          onChanged();
        } else {
          detailsBuilder_.addAllMessages(values);
        }
        return this;
      }
      public Builder clearDetails() {
        if (detailsBuilder_ == null) {
          details_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000200);
          onChanged();
        } else {
          detailsBuilder_.clear();
        }
        return this;
      }
      public Builder removeDetails(int index) {
        if (detailsBuilder_ == null) {
          ensureDetailsIsMutable();
          details_.remove(index);
          onChanged();
        } else {
          detailsBuilder_.remove(index);
        }
        return this;
      }
      public com.mobile.api.proto.MAppLibrary.MBookDetail.Builder getDetailsBuilder(
          int index) {
        return getDetailsFieldBuilder().getBuilder(index);
      }
      public com.mobile.api.proto.MAppLibrary.MBookDetailOrBuilder getDetailsOrBuilder(
          int index) {
        if (detailsBuilder_ == null) {
          return details_.get(index);  } else {
          return detailsBuilder_.getMessageOrBuilder(index);
        }
      }
      public java.util.List<? extends com.mobile.api.proto.MAppLibrary.MBookDetailOrBuilder> 
           getDetailsOrBuilderList() {
        if (detailsBuilder_ != null) {
          return detailsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(details_);
        }
      }
      public com.mobile.api.proto.MAppLibrary.MBookDetail.Builder addDetailsBuilder() {
        return getDetailsFieldBuilder().addBuilder(
            com.mobile.api.proto.MAppLibrary.MBookDetail.getDefaultInstance());
      }
      public com.mobile.api.proto.MAppLibrary.MBookDetail.Builder addDetailsBuilder(
          int index) {
        return getDetailsFieldBuilder().addBuilder(
            index, com.mobile.api.proto.MAppLibrary.MBookDetail.getDefaultInstance());
      }
      public java.util.List<com.mobile.api.proto.MAppLibrary.MBookDetail.Builder> 
           getDetailsBuilderList() {
        return getDetailsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.mobile.api.proto.MAppLibrary.MBookDetail, com.mobile.api.proto.MAppLibrary.MBookDetail.Builder, com.mobile.api.proto.MAppLibrary.MBookDetailOrBuilder> 
          getDetailsFieldBuilder() {
        if (detailsBuilder_ == null) {
          detailsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.mobile.api.proto.MAppLibrary.MBookDetail, com.mobile.api.proto.MAppLibrary.MBookDetail.Builder, com.mobile.api.proto.MAppLibrary.MBookDetailOrBuilder>(
                  details_,
                  ((bitField0_ & 0x00000200) == 0x00000200),
                  getParentForChildren(),
                  isClean());
          details_ = null;
        }
        return detailsBuilder_;
      }
      
      // @@protoc_insertion_point(builder_scope:com.mobile.api.proto.MBook)
    }
    
    static {
      defaultInstance = new MBook(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.mobile.api.proto.MBook)
  }
  
  public interface MBookDetailOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // optional string num = 1;
    boolean hasNum();
    String getNum();
    
    // optional string code = 2;
    boolean hasCode();
    String getCode();
    
    // optional string address = 3;
    boolean hasAddress();
    String getAddress();
    
    // optional string state = 4;
    boolean hasState();
    String getState();
  }
  public static final class MBookDetail extends
      com.google.protobuf.GeneratedMessage
      implements MBookDetailOrBuilder {
    // Use MBookDetail.newBuilder() to construct.
    private MBookDetail(Builder builder) {
      super(builder);
    }
    private MBookDetail(boolean noInit) {}
    
    private static final MBookDetail defaultInstance;
    public static MBookDetail getDefaultInstance() {
      return defaultInstance;
    }
    
    public MBookDetail getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.mobile.api.proto.MAppLibrary.internal_static_com_mobile_api_proto_MBookDetail_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.mobile.api.proto.MAppLibrary.internal_static_com_mobile_api_proto_MBookDetail_fieldAccessorTable;
    }
    
    private int bitField0_;
    // optional string num = 1;
    public static final int NUM_FIELD_NUMBER = 1;
    private java.lang.Object num_;
    public boolean hasNum() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getNum() {
      java.lang.Object ref = num_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          num_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getNumBytes() {
      java.lang.Object ref = num_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        num_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string code = 2;
    public static final int CODE_FIELD_NUMBER = 2;
    private java.lang.Object code_;
    public boolean hasCode() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getCode() {
      java.lang.Object ref = code_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          code_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getCodeBytes() {
      java.lang.Object ref = code_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        code_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string address = 3;
    public static final int ADDRESS_FIELD_NUMBER = 3;
    private java.lang.Object address_;
    public boolean hasAddress() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public String getAddress() {
      java.lang.Object ref = address_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          address_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getAddressBytes() {
      java.lang.Object ref = address_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        address_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string state = 4;
    public static final int STATE_FIELD_NUMBER = 4;
    private java.lang.Object state_;
    public boolean hasState() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public String getState() {
      java.lang.Object ref = state_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          state_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getStateBytes() {
      java.lang.Object ref = state_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        state_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    private void initFields() {
      num_ = "";
      code_ = "";
      address_ = "";
      state_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getNumBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getCodeBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getAddressBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getStateBytes());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getNumBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getCodeBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getAddressBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getStateBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.mobile.api.proto.MAppLibrary.MBookDetail parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.mobile.api.proto.MAppLibrary.MBookDetail parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.mobile.api.proto.MAppLibrary.MBookDetail parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.mobile.api.proto.MAppLibrary.MBookDetail parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.mobile.api.proto.MAppLibrary.MBookDetail parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.mobile.api.proto.MAppLibrary.MBookDetail parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.mobile.api.proto.MAppLibrary.MBookDetail parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.mobile.api.proto.MAppLibrary.MBookDetail parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.mobile.api.proto.MAppLibrary.MBookDetail parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.mobile.api.proto.MAppLibrary.MBookDetail parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.mobile.api.proto.MAppLibrary.MBookDetail prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.mobile.api.proto.MAppLibrary.MBookDetailOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.mobile.api.proto.MAppLibrary.internal_static_com_mobile_api_proto_MBookDetail_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.mobile.api.proto.MAppLibrary.internal_static_com_mobile_api_proto_MBookDetail_fieldAccessorTable;
      }
      
      // Construct using com.mobile.api.proto.MAppLibrary.MBookDetail.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        num_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        code_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        address_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        state_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.mobile.api.proto.MAppLibrary.MBookDetail.getDescriptor();
      }
      
      public com.mobile.api.proto.MAppLibrary.MBookDetail getDefaultInstanceForType() {
        return com.mobile.api.proto.MAppLibrary.MBookDetail.getDefaultInstance();
      }
      
      public com.mobile.api.proto.MAppLibrary.MBookDetail build() {
        com.mobile.api.proto.MAppLibrary.MBookDetail result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.mobile.api.proto.MAppLibrary.MBookDetail buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.mobile.api.proto.MAppLibrary.MBookDetail result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.mobile.api.proto.MAppLibrary.MBookDetail buildPartial() {
        com.mobile.api.proto.MAppLibrary.MBookDetail result = new com.mobile.api.proto.MAppLibrary.MBookDetail(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.num_ = num_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.code_ = code_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.address_ = address_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.state_ = state_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.mobile.api.proto.MAppLibrary.MBookDetail) {
          return mergeFrom((com.mobile.api.proto.MAppLibrary.MBookDetail)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.mobile.api.proto.MAppLibrary.MBookDetail other) {
        if (other == com.mobile.api.proto.MAppLibrary.MBookDetail.getDefaultInstance()) return this;
        if (other.hasNum()) {
          setNum(other.getNum());
        }
        if (other.hasCode()) {
          setCode(other.getCode());
        }
        if (other.hasAddress()) {
          setAddress(other.getAddress());
        }
        if (other.hasState()) {
          setState(other.getState());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              num_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              code_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              address_ = input.readBytes();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              state_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional string num = 1;
      private java.lang.Object num_ = "";
      public boolean hasNum() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getNum() {
        java.lang.Object ref = num_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          num_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setNum(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        num_ = value;
        onChanged();
        return this;
      }
      public Builder clearNum() {
        bitField0_ = (bitField0_ & ~0x00000001);
        num_ = getDefaultInstance().getNum();
        onChanged();
        return this;
      }
      void setNum(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        num_ = value;
        onChanged();
      }
      
      // optional string code = 2;
      private java.lang.Object code_ = "";
      public boolean hasCode() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getCode() {
        java.lang.Object ref = code_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          code_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setCode(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        code_ = value;
        onChanged();
        return this;
      }
      public Builder clearCode() {
        bitField0_ = (bitField0_ & ~0x00000002);
        code_ = getDefaultInstance().getCode();
        onChanged();
        return this;
      }
      void setCode(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000002;
        code_ = value;
        onChanged();
      }
      
      // optional string address = 3;
      private java.lang.Object address_ = "";
      public boolean hasAddress() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public String getAddress() {
        java.lang.Object ref = address_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          address_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setAddress(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        address_ = value;
        onChanged();
        return this;
      }
      public Builder clearAddress() {
        bitField0_ = (bitField0_ & ~0x00000004);
        address_ = getDefaultInstance().getAddress();
        onChanged();
        return this;
      }
      void setAddress(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000004;
        address_ = value;
        onChanged();
      }
      
      // optional string state = 4;
      private java.lang.Object state_ = "";
      public boolean hasState() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public String getState() {
        java.lang.Object ref = state_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          state_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setState(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        state_ = value;
        onChanged();
        return this;
      }
      public Builder clearState() {
        bitField0_ = (bitField0_ & ~0x00000008);
        state_ = getDefaultInstance().getState();
        onChanged();
        return this;
      }
      void setState(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000008;
        state_ = value;
        onChanged();
      }
      
      // @@protoc_insertion_point(builder_scope:com.mobile.api.proto.MBookDetail)
    }
    
    static {
      defaultInstance = new MBookDetail(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.mobile.api.proto.MBookDetail)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_mobile_api_proto_MBookList_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_mobile_api_proto_MBookList_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_mobile_api_proto_MBook_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_mobile_api_proto_MBook_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_mobile_api_proto_MBookDetail_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_mobile_api_proto_MBookDetail_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022zsnd_library.proto\022\024com.mobile.api.pro" +
      "to\"P\n\tMBookList\022)\n\004news\030\001 \003(\0132\033.com.mobi" +
      "le.api.proto.MBook\022\013\n\003cnt\030\002 \001(\005\022\013\n\003img\030\003" +
      " \001(\014\"\321\001\n\005MBook\022\n\n\002id\030\001 \001(\t\022\r\n\005title\030\002 \001(" +
      "\t\022\016\n\006author\030\003 \001(\t\022\017\n\007publish\030\004 \001(\t\022\r\n\005to" +
      "tal\030\005 \001(\005\022\021\n\tcanBorrow\030\006 \001(\005\022\022\n\nborrowTi" +
      "me\030\007 \001(\t\022\020\n\010backTime\030\010 \001(\t\022\020\n\010canRenew\030\t" +
      " \001(\005\0222\n\007details\030\n \003(\0132!.com.mobile.api.p" +
      "roto.MBookDetail\"H\n\013MBookDetail\022\013\n\003num\030\001" +
      " \001(\t\022\014\n\004code\030\002 \001(\t\022\017\n\007address\030\003 \001(\t\022\r\n\005s",
      "tate\030\004 \001(\tB\rB\013MAppLibrary"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_mobile_api_proto_MBookList_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_mobile_api_proto_MBookList_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_mobile_api_proto_MBookList_descriptor,
              new java.lang.String[] { "News", "Cnt", "Img", },
              com.mobile.api.proto.MAppLibrary.MBookList.class,
              com.mobile.api.proto.MAppLibrary.MBookList.Builder.class);
          internal_static_com_mobile_api_proto_MBook_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_com_mobile_api_proto_MBook_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_mobile_api_proto_MBook_descriptor,
              new java.lang.String[] { "Id", "Title", "Author", "Publish", "Total", "CanBorrow", "BorrowTime", "BackTime", "CanRenew", "Details", },
              com.mobile.api.proto.MAppLibrary.MBook.class,
              com.mobile.api.proto.MAppLibrary.MBook.Builder.class);
          internal_static_com_mobile_api_proto_MBookDetail_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_com_mobile_api_proto_MBookDetail_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_mobile_api_proto_MBookDetail_descriptor,
              new java.lang.String[] { "Num", "Code", "Address", "State", },
              com.mobile.api.proto.MAppLibrary.MBookDetail.class,
              com.mobile.api.proto.MAppLibrary.MBookDetail.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
