// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: zsnd_essence.proto

package com.mobile.api.proto;

public final class MLost {
  private MLost() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface MLostAndFoundListOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // repeated .com.mobile.api.proto.MLostAndFound lf = 1;
    java.util.List<com.mobile.api.proto.MLost.MLostAndFound> 
        getLfList();
    com.mobile.api.proto.MLost.MLostAndFound getLf(int index);
    int getLfCount();
    java.util.List<? extends com.mobile.api.proto.MLost.MLostAndFoundOrBuilder> 
        getLfOrBuilderList();
    com.mobile.api.proto.MLost.MLostAndFoundOrBuilder getLfOrBuilder(
        int index);
  }
  public static final class MLostAndFoundList extends
      com.google.protobuf.GeneratedMessage
      implements MLostAndFoundListOrBuilder {
    // Use MLostAndFoundList.newBuilder() to construct.
    private MLostAndFoundList(Builder builder) {
      super(builder);
    }
    private MLostAndFoundList(boolean noInit) {}
    
    private static final MLostAndFoundList defaultInstance;
    public static MLostAndFoundList getDefaultInstance() {
      return defaultInstance;
    }
    
    public MLostAndFoundList getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.mobile.api.proto.MLost.internal_static_com_mobile_api_proto_MLostAndFoundList_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.mobile.api.proto.MLost.internal_static_com_mobile_api_proto_MLostAndFoundList_fieldAccessorTable;
    }
    
    // repeated .com.mobile.api.proto.MLostAndFound lf = 1;
    public static final int LF_FIELD_NUMBER = 1;
    private java.util.List<com.mobile.api.proto.MLost.MLostAndFound> lf_;
    public java.util.List<com.mobile.api.proto.MLost.MLostAndFound> getLfList() {
      return lf_;
    }
    public java.util.List<? extends com.mobile.api.proto.MLost.MLostAndFoundOrBuilder> 
        getLfOrBuilderList() {
      return lf_;
    }
    public int getLfCount() {
      return lf_.size();
    }
    public com.mobile.api.proto.MLost.MLostAndFound getLf(int index) {
      return lf_.get(index);
    }
    public com.mobile.api.proto.MLost.MLostAndFoundOrBuilder getLfOrBuilder(
        int index) {
      return lf_.get(index);
    }
    
    private void initFields() {
      lf_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < lf_.size(); i++) {
        output.writeMessage(1, lf_.get(i));
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      for (int i = 0; i < lf_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, lf_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.mobile.api.proto.MLost.MLostAndFoundList parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.mobile.api.proto.MLost.MLostAndFoundList parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.mobile.api.proto.MLost.MLostAndFoundList parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.mobile.api.proto.MLost.MLostAndFoundList parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.mobile.api.proto.MLost.MLostAndFoundList parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.mobile.api.proto.MLost.MLostAndFoundList parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.mobile.api.proto.MLost.MLostAndFoundList parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.mobile.api.proto.MLost.MLostAndFoundList parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.mobile.api.proto.MLost.MLostAndFoundList parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.mobile.api.proto.MLost.MLostAndFoundList parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.mobile.api.proto.MLost.MLostAndFoundList prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.mobile.api.proto.MLost.MLostAndFoundListOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.mobile.api.proto.MLost.internal_static_com_mobile_api_proto_MLostAndFoundList_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.mobile.api.proto.MLost.internal_static_com_mobile_api_proto_MLostAndFoundList_fieldAccessorTable;
      }
      
      // Construct using com.mobile.api.proto.MLost.MLostAndFoundList.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getLfFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        if (lfBuilder_ == null) {
          lf_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          lfBuilder_.clear();
        }
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.mobile.api.proto.MLost.MLostAndFoundList.getDescriptor();
      }
      
      public com.mobile.api.proto.MLost.MLostAndFoundList getDefaultInstanceForType() {
        return com.mobile.api.proto.MLost.MLostAndFoundList.getDefaultInstance();
      }
      
      public com.mobile.api.proto.MLost.MLostAndFoundList build() {
        com.mobile.api.proto.MLost.MLostAndFoundList result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.mobile.api.proto.MLost.MLostAndFoundList buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.mobile.api.proto.MLost.MLostAndFoundList result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.mobile.api.proto.MLost.MLostAndFoundList buildPartial() {
        com.mobile.api.proto.MLost.MLostAndFoundList result = new com.mobile.api.proto.MLost.MLostAndFoundList(this);
        int from_bitField0_ = bitField0_;
        if (lfBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            lf_ = java.util.Collections.unmodifiableList(lf_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.lf_ = lf_;
        } else {
          result.lf_ = lfBuilder_.build();
        }
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.mobile.api.proto.MLost.MLostAndFoundList) {
          return mergeFrom((com.mobile.api.proto.MLost.MLostAndFoundList)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.mobile.api.proto.MLost.MLostAndFoundList other) {
        if (other == com.mobile.api.proto.MLost.MLostAndFoundList.getDefaultInstance()) return this;
        if (lfBuilder_ == null) {
          if (!other.lf_.isEmpty()) {
            if (lf_.isEmpty()) {
              lf_ = other.lf_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureLfIsMutable();
              lf_.addAll(other.lf_);
            }
            onChanged();
          }
        } else {
          if (!other.lf_.isEmpty()) {
            if (lfBuilder_.isEmpty()) {
              lfBuilder_.dispose();
              lfBuilder_ = null;
              lf_ = other.lf_;
              bitField0_ = (bitField0_ & ~0x00000001);
              lfBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getLfFieldBuilder() : null;
            } else {
              lfBuilder_.addAllMessages(other.lf_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              com.mobile.api.proto.MLost.MLostAndFound.Builder subBuilder = com.mobile.api.proto.MLost.MLostAndFound.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addLf(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // repeated .com.mobile.api.proto.MLostAndFound lf = 1;
      private java.util.List<com.mobile.api.proto.MLost.MLostAndFound> lf_ =
        java.util.Collections.emptyList();
      private void ensureLfIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          lf_ = new java.util.ArrayList<com.mobile.api.proto.MLost.MLostAndFound>(lf_);
          bitField0_ |= 0x00000001;
         }
      }
      
      private com.google.protobuf.RepeatedFieldBuilder<
          com.mobile.api.proto.MLost.MLostAndFound, com.mobile.api.proto.MLost.MLostAndFound.Builder, com.mobile.api.proto.MLost.MLostAndFoundOrBuilder> lfBuilder_;
      
      public java.util.List<com.mobile.api.proto.MLost.MLostAndFound> getLfList() {
        if (lfBuilder_ == null) {
          return java.util.Collections.unmodifiableList(lf_);
        } else {
          return lfBuilder_.getMessageList();
        }
      }
      public int getLfCount() {
        if (lfBuilder_ == null) {
          return lf_.size();
        } else {
          return lfBuilder_.getCount();
        }
      }
      public com.mobile.api.proto.MLost.MLostAndFound getLf(int index) {
        if (lfBuilder_ == null) {
          return lf_.get(index);
        } else {
          return lfBuilder_.getMessage(index);
        }
      }
      public Builder setLf(
          int index, com.mobile.api.proto.MLost.MLostAndFound value) {
        if (lfBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureLfIsMutable();
          lf_.set(index, value);
          onChanged();
        } else {
          lfBuilder_.setMessage(index, value);
        }
        return this;
      }
      public Builder setLf(
          int index, com.mobile.api.proto.MLost.MLostAndFound.Builder builderForValue) {
        if (lfBuilder_ == null) {
          ensureLfIsMutable();
          lf_.set(index, builderForValue.build());
          onChanged();
        } else {
          lfBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addLf(com.mobile.api.proto.MLost.MLostAndFound value) {
        if (lfBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureLfIsMutable();
          lf_.add(value);
          onChanged();
        } else {
          lfBuilder_.addMessage(value);
        }
        return this;
      }
      public Builder addLf(
          int index, com.mobile.api.proto.MLost.MLostAndFound value) {
        if (lfBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureLfIsMutable();
          lf_.add(index, value);
          onChanged();
        } else {
          lfBuilder_.addMessage(index, value);
        }
        return this;
      }
      public Builder addLf(
          com.mobile.api.proto.MLost.MLostAndFound.Builder builderForValue) {
        if (lfBuilder_ == null) {
          ensureLfIsMutable();
          lf_.add(builderForValue.build());
          onChanged();
        } else {
          lfBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      public Builder addLf(
          int index, com.mobile.api.proto.MLost.MLostAndFound.Builder builderForValue) {
        if (lfBuilder_ == null) {
          ensureLfIsMutable();
          lf_.add(index, builderForValue.build());
          onChanged();
        } else {
          lfBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAllLf(
          java.lang.Iterable<? extends com.mobile.api.proto.MLost.MLostAndFound> values) {
        if (lfBuilder_ == null) {
          ensureLfIsMutable();
          super.addAll(values, lf_);
          onChanged();
        } else {
          lfBuilder_.addAllMessages(values);
        }
        return this;
      }
      public Builder clearLf() {
        if (lfBuilder_ == null) {
          lf_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          lfBuilder_.clear();
        }
        return this;
      }
      public Builder removeLf(int index) {
        if (lfBuilder_ == null) {
          ensureLfIsMutable();
          lf_.remove(index);
          onChanged();
        } else {
          lfBuilder_.remove(index);
        }
        return this;
      }
      public com.mobile.api.proto.MLost.MLostAndFound.Builder getLfBuilder(
          int index) {
        return getLfFieldBuilder().getBuilder(index);
      }
      public com.mobile.api.proto.MLost.MLostAndFoundOrBuilder getLfOrBuilder(
          int index) {
        if (lfBuilder_ == null) {
          return lf_.get(index);  } else {
          return lfBuilder_.getMessageOrBuilder(index);
        }
      }
      public java.util.List<? extends com.mobile.api.proto.MLost.MLostAndFoundOrBuilder> 
           getLfOrBuilderList() {
        if (lfBuilder_ != null) {
          return lfBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(lf_);
        }
      }
      public com.mobile.api.proto.MLost.MLostAndFound.Builder addLfBuilder() {
        return getLfFieldBuilder().addBuilder(
            com.mobile.api.proto.MLost.MLostAndFound.getDefaultInstance());
      }
      public com.mobile.api.proto.MLost.MLostAndFound.Builder addLfBuilder(
          int index) {
        return getLfFieldBuilder().addBuilder(
            index, com.mobile.api.proto.MLost.MLostAndFound.getDefaultInstance());
      }
      public java.util.List<com.mobile.api.proto.MLost.MLostAndFound.Builder> 
           getLfBuilderList() {
        return getLfFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.mobile.api.proto.MLost.MLostAndFound, com.mobile.api.proto.MLost.MLostAndFound.Builder, com.mobile.api.proto.MLost.MLostAndFoundOrBuilder> 
          getLfFieldBuilder() {
        if (lfBuilder_ == null) {
          lfBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.mobile.api.proto.MLost.MLostAndFound, com.mobile.api.proto.MLost.MLostAndFound.Builder, com.mobile.api.proto.MLost.MLostAndFoundOrBuilder>(
                  lf_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          lf_ = null;
        }
        return lfBuilder_;
      }
      
      // @@protoc_insertion_point(builder_scope:com.mobile.api.proto.MLostAndFoundList)
    }
    
    static {
      defaultInstance = new MLostAndFoundList(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.mobile.api.proto.MLostAndFoundList)
  }
  
  public interface MLostAndFoundOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // optional string id = 1;
    boolean hasId();
    String getId();
    
    // optional string address = 2;
    boolean hasAddress();
    String getAddress();
    
    // optional string desc = 3;
    boolean hasDesc();
    String getDesc();
    
    // optional string userid = 4;
    boolean hasUserid();
    String getUserid();
    
    // optional string nickname = 5;
    boolean hasNickname();
    String getNickname();
    
    // optional string contact = 6;
    boolean hasContact();
    String getContact();
    
    // optional string time = 7;
    boolean hasTime();
    String getTime();
    
    // repeated string img = 8;
    java.util.List<String> getImgList();
    int getImgCount();
    String getImg(int index);
  }
  public static final class MLostAndFound extends
      com.google.protobuf.GeneratedMessage
      implements MLostAndFoundOrBuilder {
    // Use MLostAndFound.newBuilder() to construct.
    private MLostAndFound(Builder builder) {
      super(builder);
    }
    private MLostAndFound(boolean noInit) {}
    
    private static final MLostAndFound defaultInstance;
    public static MLostAndFound getDefaultInstance() {
      return defaultInstance;
    }
    
    public MLostAndFound getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.mobile.api.proto.MLost.internal_static_com_mobile_api_proto_MLostAndFound_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.mobile.api.proto.MLost.internal_static_com_mobile_api_proto_MLostAndFound_fieldAccessorTable;
    }
    
    private int bitField0_;
    // optional string id = 1;
    public static final int ID_FIELD_NUMBER = 1;
    private java.lang.Object id_;
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getId() {
      java.lang.Object ref = id_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          id_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string address = 2;
    public static final int ADDRESS_FIELD_NUMBER = 2;
    private java.lang.Object address_;
    public boolean hasAddress() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getAddress() {
      java.lang.Object ref = address_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          address_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getAddressBytes() {
      java.lang.Object ref = address_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        address_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string desc = 3;
    public static final int DESC_FIELD_NUMBER = 3;
    private java.lang.Object desc_;
    public boolean hasDesc() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public String getDesc() {
      java.lang.Object ref = desc_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          desc_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getDescBytes() {
      java.lang.Object ref = desc_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        desc_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string userid = 4;
    public static final int USERID_FIELD_NUMBER = 4;
    private java.lang.Object userid_;
    public boolean hasUserid() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public String getUserid() {
      java.lang.Object ref = userid_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          userid_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getUseridBytes() {
      java.lang.Object ref = userid_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        userid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string nickname = 5;
    public static final int NICKNAME_FIELD_NUMBER = 5;
    private java.lang.Object nickname_;
    public boolean hasNickname() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    public String getNickname() {
      java.lang.Object ref = nickname_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          nickname_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getNicknameBytes() {
      java.lang.Object ref = nickname_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        nickname_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string contact = 6;
    public static final int CONTACT_FIELD_NUMBER = 6;
    private java.lang.Object contact_;
    public boolean hasContact() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    public String getContact() {
      java.lang.Object ref = contact_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          contact_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getContactBytes() {
      java.lang.Object ref = contact_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        contact_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string time = 7;
    public static final int TIME_FIELD_NUMBER = 7;
    private java.lang.Object time_;
    public boolean hasTime() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    public String getTime() {
      java.lang.Object ref = time_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          time_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getTimeBytes() {
      java.lang.Object ref = time_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        time_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // repeated string img = 8;
    public static final int IMG_FIELD_NUMBER = 8;
    private com.google.protobuf.LazyStringList img_;
    public java.util.List<String>
        getImgList() {
      return img_;
    }
    public int getImgCount() {
      return img_.size();
    }
    public String getImg(int index) {
      return img_.get(index);
    }
    
    private void initFields() {
      id_ = "";
      address_ = "";
      desc_ = "";
      userid_ = "";
      nickname_ = "";
      contact_ = "";
      time_ = "";
      img_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getAddressBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getDescBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getUseridBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(5, getNicknameBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeBytes(6, getContactBytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeBytes(7, getTimeBytes());
      }
      for (int i = 0; i < img_.size(); i++) {
        output.writeBytes(8, img_.getByteString(i));
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getAddressBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getDescBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getUseridBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, getNicknameBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, getContactBytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(7, getTimeBytes());
      }
      {
        int dataSize = 0;
        for (int i = 0; i < img_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(img_.getByteString(i));
        }
        size += dataSize;
        size += 1 * getImgList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.mobile.api.proto.MLost.MLostAndFound parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.mobile.api.proto.MLost.MLostAndFound parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.mobile.api.proto.MLost.MLostAndFound parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.mobile.api.proto.MLost.MLostAndFound parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.mobile.api.proto.MLost.MLostAndFound parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.mobile.api.proto.MLost.MLostAndFound parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.mobile.api.proto.MLost.MLostAndFound parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.mobile.api.proto.MLost.MLostAndFound parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.mobile.api.proto.MLost.MLostAndFound parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.mobile.api.proto.MLost.MLostAndFound parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.mobile.api.proto.MLost.MLostAndFound prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.mobile.api.proto.MLost.MLostAndFoundOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.mobile.api.proto.MLost.internal_static_com_mobile_api_proto_MLostAndFound_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.mobile.api.proto.MLost.internal_static_com_mobile_api_proto_MLostAndFound_fieldAccessorTable;
      }
      
      // Construct using com.mobile.api.proto.MLost.MLostAndFound.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        id_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        address_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        desc_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        userid_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        nickname_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        contact_ = "";
        bitField0_ = (bitField0_ & ~0x00000020);
        time_ = "";
        bitField0_ = (bitField0_ & ~0x00000040);
        img_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000080);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.mobile.api.proto.MLost.MLostAndFound.getDescriptor();
      }
      
      public com.mobile.api.proto.MLost.MLostAndFound getDefaultInstanceForType() {
        return com.mobile.api.proto.MLost.MLostAndFound.getDefaultInstance();
      }
      
      public com.mobile.api.proto.MLost.MLostAndFound build() {
        com.mobile.api.proto.MLost.MLostAndFound result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.mobile.api.proto.MLost.MLostAndFound buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.mobile.api.proto.MLost.MLostAndFound result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.mobile.api.proto.MLost.MLostAndFound buildPartial() {
        com.mobile.api.proto.MLost.MLostAndFound result = new com.mobile.api.proto.MLost.MLostAndFound(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.address_ = address_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.desc_ = desc_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.userid_ = userid_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.nickname_ = nickname_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.contact_ = contact_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.time_ = time_;
        if (((bitField0_ & 0x00000080) == 0x00000080)) {
          img_ = new com.google.protobuf.UnmodifiableLazyStringList(
              img_);
          bitField0_ = (bitField0_ & ~0x00000080);
        }
        result.img_ = img_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.mobile.api.proto.MLost.MLostAndFound) {
          return mergeFrom((com.mobile.api.proto.MLost.MLostAndFound)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.mobile.api.proto.MLost.MLostAndFound other) {
        if (other == com.mobile.api.proto.MLost.MLostAndFound.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasAddress()) {
          setAddress(other.getAddress());
        }
        if (other.hasDesc()) {
          setDesc(other.getDesc());
        }
        if (other.hasUserid()) {
          setUserid(other.getUserid());
        }
        if (other.hasNickname()) {
          setNickname(other.getNickname());
        }
        if (other.hasContact()) {
          setContact(other.getContact());
        }
        if (other.hasTime()) {
          setTime(other.getTime());
        }
        if (!other.img_.isEmpty()) {
          if (img_.isEmpty()) {
            img_ = other.img_;
            bitField0_ = (bitField0_ & ~0x00000080);
          } else {
            ensureImgIsMutable();
            img_.addAll(other.img_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              id_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              address_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              desc_ = input.readBytes();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              userid_ = input.readBytes();
              break;
            }
            case 42: {
              bitField0_ |= 0x00000010;
              nickname_ = input.readBytes();
              break;
            }
            case 50: {
              bitField0_ |= 0x00000020;
              contact_ = input.readBytes();
              break;
            }
            case 58: {
              bitField0_ |= 0x00000040;
              time_ = input.readBytes();
              break;
            }
            case 66: {
              ensureImgIsMutable();
              img_.add(input.readBytes());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional string id = 1;
      private java.lang.Object id_ = "";
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getId() {
        java.lang.Object ref = id_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          id_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setId(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = getDefaultInstance().getId();
        onChanged();
        return this;
      }
      void setId(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
      }
      
      // optional string address = 2;
      private java.lang.Object address_ = "";
      public boolean hasAddress() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getAddress() {
        java.lang.Object ref = address_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          address_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setAddress(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        address_ = value;
        onChanged();
        return this;
      }
      public Builder clearAddress() {
        bitField0_ = (bitField0_ & ~0x00000002);
        address_ = getDefaultInstance().getAddress();
        onChanged();
        return this;
      }
      void setAddress(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000002;
        address_ = value;
        onChanged();
      }
      
      // optional string desc = 3;
      private java.lang.Object desc_ = "";
      public boolean hasDesc() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public String getDesc() {
        java.lang.Object ref = desc_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          desc_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setDesc(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        desc_ = value;
        onChanged();
        return this;
      }
      public Builder clearDesc() {
        bitField0_ = (bitField0_ & ~0x00000004);
        desc_ = getDefaultInstance().getDesc();
        onChanged();
        return this;
      }
      void setDesc(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000004;
        desc_ = value;
        onChanged();
      }
      
      // optional string userid = 4;
      private java.lang.Object userid_ = "";
      public boolean hasUserid() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public String getUserid() {
        java.lang.Object ref = userid_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          userid_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setUserid(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        userid_ = value;
        onChanged();
        return this;
      }
      public Builder clearUserid() {
        bitField0_ = (bitField0_ & ~0x00000008);
        userid_ = getDefaultInstance().getUserid();
        onChanged();
        return this;
      }
      void setUserid(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000008;
        userid_ = value;
        onChanged();
      }
      
      // optional string nickname = 5;
      private java.lang.Object nickname_ = "";
      public boolean hasNickname() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      public String getNickname() {
        java.lang.Object ref = nickname_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          nickname_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setNickname(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        nickname_ = value;
        onChanged();
        return this;
      }
      public Builder clearNickname() {
        bitField0_ = (bitField0_ & ~0x00000010);
        nickname_ = getDefaultInstance().getNickname();
        onChanged();
        return this;
      }
      void setNickname(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000010;
        nickname_ = value;
        onChanged();
      }
      
      // optional string contact = 6;
      private java.lang.Object contact_ = "";
      public boolean hasContact() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      public String getContact() {
        java.lang.Object ref = contact_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          contact_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setContact(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        contact_ = value;
        onChanged();
        return this;
      }
      public Builder clearContact() {
        bitField0_ = (bitField0_ & ~0x00000020);
        contact_ = getDefaultInstance().getContact();
        onChanged();
        return this;
      }
      void setContact(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000020;
        contact_ = value;
        onChanged();
      }
      
      // optional string time = 7;
      private java.lang.Object time_ = "";
      public boolean hasTime() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      public String getTime() {
        java.lang.Object ref = time_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          time_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setTime(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        time_ = value;
        onChanged();
        return this;
      }
      public Builder clearTime() {
        bitField0_ = (bitField0_ & ~0x00000040);
        time_ = getDefaultInstance().getTime();
        onChanged();
        return this;
      }
      void setTime(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000040;
        time_ = value;
        onChanged();
      }
      
      // repeated string img = 8;
      private com.google.protobuf.LazyStringList img_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureImgIsMutable() {
        if (!((bitField0_ & 0x00000080) == 0x00000080)) {
          img_ = new com.google.protobuf.LazyStringArrayList(img_);
          bitField0_ |= 0x00000080;
         }
      }
      public java.util.List<String>
          getImgList() {
        return java.util.Collections.unmodifiableList(img_);
      }
      public int getImgCount() {
        return img_.size();
      }
      public String getImg(int index) {
        return img_.get(index);
      }
      public Builder setImg(
          int index, String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureImgIsMutable();
        img_.set(index, value);
        onChanged();
        return this;
      }
      public Builder addImg(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureImgIsMutable();
        img_.add(value);
        onChanged();
        return this;
      }
      public Builder addAllImg(
          java.lang.Iterable<String> values) {
        ensureImgIsMutable();
        super.addAll(values, img_);
        onChanged();
        return this;
      }
      public Builder clearImg() {
        img_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000080);
        onChanged();
        return this;
      }
      void addImg(com.google.protobuf.ByteString value) {
        ensureImgIsMutable();
        img_.add(value);
        onChanged();
      }
      
      // @@protoc_insertion_point(builder_scope:com.mobile.api.proto.MLostAndFound)
    }
    
    static {
      defaultInstance = new MLostAndFound(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.mobile.api.proto.MLostAndFound)
  }
  
  public interface MAddLostOrFoundOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // optional int32 type = 1;
    boolean hasType();
    int getType();
    
    // optional string address = 2;
    boolean hasAddress();
    String getAddress();
    
    // optional string desc = 3;
    boolean hasDesc();
    String getDesc();
    
    // optional string contact = 4;
    boolean hasContact();
    String getContact();
    
    // optional string time = 5;
    boolean hasTime();
    String getTime();
    
    // optional bytes img1 = 6;
    boolean hasImg1();
    com.google.protobuf.ByteString getImg1();
    
    // optional bytes img2 = 7;
    boolean hasImg2();
    com.google.protobuf.ByteString getImg2();
    
    // optional bytes img3 = 8;
    boolean hasImg3();
    com.google.protobuf.ByteString getImg3();
    
    // optional bytes img4 = 9;
    boolean hasImg4();
    com.google.protobuf.ByteString getImg4();
  }
  public static final class MAddLostOrFound extends
      com.google.protobuf.GeneratedMessage
      implements MAddLostOrFoundOrBuilder {
    // Use MAddLostOrFound.newBuilder() to construct.
    private MAddLostOrFound(Builder builder) {
      super(builder);
    }
    private MAddLostOrFound(boolean noInit) {}
    
    private static final MAddLostOrFound defaultInstance;
    public static MAddLostOrFound getDefaultInstance() {
      return defaultInstance;
    }
    
    public MAddLostOrFound getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.mobile.api.proto.MLost.internal_static_com_mobile_api_proto_MAddLostOrFound_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.mobile.api.proto.MLost.internal_static_com_mobile_api_proto_MAddLostOrFound_fieldAccessorTable;
    }
    
    private int bitField0_;
    // optional int32 type = 1;
    public static final int TYPE_FIELD_NUMBER = 1;
    private int type_;
    public boolean hasType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public int getType() {
      return type_;
    }
    
    // optional string address = 2;
    public static final int ADDRESS_FIELD_NUMBER = 2;
    private java.lang.Object address_;
    public boolean hasAddress() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getAddress() {
      java.lang.Object ref = address_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          address_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getAddressBytes() {
      java.lang.Object ref = address_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        address_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string desc = 3;
    public static final int DESC_FIELD_NUMBER = 3;
    private java.lang.Object desc_;
    public boolean hasDesc() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public String getDesc() {
      java.lang.Object ref = desc_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          desc_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getDescBytes() {
      java.lang.Object ref = desc_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        desc_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string contact = 4;
    public static final int CONTACT_FIELD_NUMBER = 4;
    private java.lang.Object contact_;
    public boolean hasContact() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public String getContact() {
      java.lang.Object ref = contact_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          contact_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getContactBytes() {
      java.lang.Object ref = contact_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        contact_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string time = 5;
    public static final int TIME_FIELD_NUMBER = 5;
    private java.lang.Object time_;
    public boolean hasTime() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    public String getTime() {
      java.lang.Object ref = time_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          time_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getTimeBytes() {
      java.lang.Object ref = time_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        time_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional bytes img1 = 6;
    public static final int IMG1_FIELD_NUMBER = 6;
    private com.google.protobuf.ByteString img1_;
    public boolean hasImg1() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    public com.google.protobuf.ByteString getImg1() {
      return img1_;
    }
    
    // optional bytes img2 = 7;
    public static final int IMG2_FIELD_NUMBER = 7;
    private com.google.protobuf.ByteString img2_;
    public boolean hasImg2() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    public com.google.protobuf.ByteString getImg2() {
      return img2_;
    }
    
    // optional bytes img3 = 8;
    public static final int IMG3_FIELD_NUMBER = 8;
    private com.google.protobuf.ByteString img3_;
    public boolean hasImg3() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    public com.google.protobuf.ByteString getImg3() {
      return img3_;
    }
    
    // optional bytes img4 = 9;
    public static final int IMG4_FIELD_NUMBER = 9;
    private com.google.protobuf.ByteString img4_;
    public boolean hasImg4() {
      return ((bitField0_ & 0x00000100) == 0x00000100);
    }
    public com.google.protobuf.ByteString getImg4() {
      return img4_;
    }
    
    private void initFields() {
      type_ = 0;
      address_ = "";
      desc_ = "";
      contact_ = "";
      time_ = "";
      img1_ = com.google.protobuf.ByteString.EMPTY;
      img2_ = com.google.protobuf.ByteString.EMPTY;
      img3_ = com.google.protobuf.ByteString.EMPTY;
      img4_ = com.google.protobuf.ByteString.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, type_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getAddressBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getDescBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getContactBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(5, getTimeBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeBytes(6, img1_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeBytes(7, img2_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeBytes(8, img3_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        output.writeBytes(9, img4_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, type_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getAddressBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getDescBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getContactBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, getTimeBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, img1_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(7, img2_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(8, img3_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(9, img4_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.mobile.api.proto.MLost.MAddLostOrFound parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.mobile.api.proto.MLost.MAddLostOrFound parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.mobile.api.proto.MLost.MAddLostOrFound parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.mobile.api.proto.MLost.MAddLostOrFound parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.mobile.api.proto.MLost.MAddLostOrFound parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.mobile.api.proto.MLost.MAddLostOrFound parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.mobile.api.proto.MLost.MAddLostOrFound parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.mobile.api.proto.MLost.MAddLostOrFound parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.mobile.api.proto.MLost.MAddLostOrFound parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.mobile.api.proto.MLost.MAddLostOrFound parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.mobile.api.proto.MLost.MAddLostOrFound prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.mobile.api.proto.MLost.MAddLostOrFoundOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.mobile.api.proto.MLost.internal_static_com_mobile_api_proto_MAddLostOrFound_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.mobile.api.proto.MLost.internal_static_com_mobile_api_proto_MAddLostOrFound_fieldAccessorTable;
      }
      
      // Construct using com.mobile.api.proto.MLost.MAddLostOrFound.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        type_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        address_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        desc_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        contact_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        time_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        img1_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000020);
        img2_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000040);
        img3_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000080);
        img4_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000100);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.mobile.api.proto.MLost.MAddLostOrFound.getDescriptor();
      }
      
      public com.mobile.api.proto.MLost.MAddLostOrFound getDefaultInstanceForType() {
        return com.mobile.api.proto.MLost.MAddLostOrFound.getDefaultInstance();
      }
      
      public com.mobile.api.proto.MLost.MAddLostOrFound build() {
        com.mobile.api.proto.MLost.MAddLostOrFound result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.mobile.api.proto.MLost.MAddLostOrFound buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.mobile.api.proto.MLost.MAddLostOrFound result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.mobile.api.proto.MLost.MAddLostOrFound buildPartial() {
        com.mobile.api.proto.MLost.MAddLostOrFound result = new com.mobile.api.proto.MLost.MAddLostOrFound(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.type_ = type_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.address_ = address_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.desc_ = desc_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.contact_ = contact_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.time_ = time_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.img1_ = img1_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.img2_ = img2_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.img3_ = img3_;
        if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
          to_bitField0_ |= 0x00000100;
        }
        result.img4_ = img4_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.mobile.api.proto.MLost.MAddLostOrFound) {
          return mergeFrom((com.mobile.api.proto.MLost.MAddLostOrFound)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.mobile.api.proto.MLost.MAddLostOrFound other) {
        if (other == com.mobile.api.proto.MLost.MAddLostOrFound.getDefaultInstance()) return this;
        if (other.hasType()) {
          setType(other.getType());
        }
        if (other.hasAddress()) {
          setAddress(other.getAddress());
        }
        if (other.hasDesc()) {
          setDesc(other.getDesc());
        }
        if (other.hasContact()) {
          setContact(other.getContact());
        }
        if (other.hasTime()) {
          setTime(other.getTime());
        }
        if (other.hasImg1()) {
          setImg1(other.getImg1());
        }
        if (other.hasImg2()) {
          setImg2(other.getImg2());
        }
        if (other.hasImg3()) {
          setImg3(other.getImg3());
        }
        if (other.hasImg4()) {
          setImg4(other.getImg4());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              type_ = input.readInt32();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              address_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              desc_ = input.readBytes();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              contact_ = input.readBytes();
              break;
            }
            case 42: {
              bitField0_ |= 0x00000010;
              time_ = input.readBytes();
              break;
            }
            case 50: {
              bitField0_ |= 0x00000020;
              img1_ = input.readBytes();
              break;
            }
            case 58: {
              bitField0_ |= 0x00000040;
              img2_ = input.readBytes();
              break;
            }
            case 66: {
              bitField0_ |= 0x00000080;
              img3_ = input.readBytes();
              break;
            }
            case 74: {
              bitField0_ |= 0x00000100;
              img4_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional int32 type = 1;
      private int type_ ;
      public boolean hasType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public int getType() {
        return type_;
      }
      public Builder setType(int value) {
        bitField0_ |= 0x00000001;
        type_ = value;
        onChanged();
        return this;
      }
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        type_ = 0;
        onChanged();
        return this;
      }
      
      // optional string address = 2;
      private java.lang.Object address_ = "";
      public boolean hasAddress() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getAddress() {
        java.lang.Object ref = address_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          address_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setAddress(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        address_ = value;
        onChanged();
        return this;
      }
      public Builder clearAddress() {
        bitField0_ = (bitField0_ & ~0x00000002);
        address_ = getDefaultInstance().getAddress();
        onChanged();
        return this;
      }
      void setAddress(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000002;
        address_ = value;
        onChanged();
      }
      
      // optional string desc = 3;
      private java.lang.Object desc_ = "";
      public boolean hasDesc() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public String getDesc() {
        java.lang.Object ref = desc_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          desc_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setDesc(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        desc_ = value;
        onChanged();
        return this;
      }
      public Builder clearDesc() {
        bitField0_ = (bitField0_ & ~0x00000004);
        desc_ = getDefaultInstance().getDesc();
        onChanged();
        return this;
      }
      void setDesc(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000004;
        desc_ = value;
        onChanged();
      }
      
      // optional string contact = 4;
      private java.lang.Object contact_ = "";
      public boolean hasContact() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public String getContact() {
        java.lang.Object ref = contact_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          contact_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setContact(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        contact_ = value;
        onChanged();
        return this;
      }
      public Builder clearContact() {
        bitField0_ = (bitField0_ & ~0x00000008);
        contact_ = getDefaultInstance().getContact();
        onChanged();
        return this;
      }
      void setContact(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000008;
        contact_ = value;
        onChanged();
      }
      
      // optional string time = 5;
      private java.lang.Object time_ = "";
      public boolean hasTime() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      public String getTime() {
        java.lang.Object ref = time_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          time_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setTime(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        time_ = value;
        onChanged();
        return this;
      }
      public Builder clearTime() {
        bitField0_ = (bitField0_ & ~0x00000010);
        time_ = getDefaultInstance().getTime();
        onChanged();
        return this;
      }
      void setTime(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000010;
        time_ = value;
        onChanged();
      }
      
      // optional bytes img1 = 6;
      private com.google.protobuf.ByteString img1_ = com.google.protobuf.ByteString.EMPTY;
      public boolean hasImg1() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      public com.google.protobuf.ByteString getImg1() {
        return img1_;
      }
      public Builder setImg1(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        img1_ = value;
        onChanged();
        return this;
      }
      public Builder clearImg1() {
        bitField0_ = (bitField0_ & ~0x00000020);
        img1_ = getDefaultInstance().getImg1();
        onChanged();
        return this;
      }
      
      // optional bytes img2 = 7;
      private com.google.protobuf.ByteString img2_ = com.google.protobuf.ByteString.EMPTY;
      public boolean hasImg2() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      public com.google.protobuf.ByteString getImg2() {
        return img2_;
      }
      public Builder setImg2(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        img2_ = value;
        onChanged();
        return this;
      }
      public Builder clearImg2() {
        bitField0_ = (bitField0_ & ~0x00000040);
        img2_ = getDefaultInstance().getImg2();
        onChanged();
        return this;
      }
      
      // optional bytes img3 = 8;
      private com.google.protobuf.ByteString img3_ = com.google.protobuf.ByteString.EMPTY;
      public boolean hasImg3() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      public com.google.protobuf.ByteString getImg3() {
        return img3_;
      }
      public Builder setImg3(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
        img3_ = value;
        onChanged();
        return this;
      }
      public Builder clearImg3() {
        bitField0_ = (bitField0_ & ~0x00000080);
        img3_ = getDefaultInstance().getImg3();
        onChanged();
        return this;
      }
      
      // optional bytes img4 = 9;
      private com.google.protobuf.ByteString img4_ = com.google.protobuf.ByteString.EMPTY;
      public boolean hasImg4() {
        return ((bitField0_ & 0x00000100) == 0x00000100);
      }
      public com.google.protobuf.ByteString getImg4() {
        return img4_;
      }
      public Builder setImg4(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000100;
        img4_ = value;
        onChanged();
        return this;
      }
      public Builder clearImg4() {
        bitField0_ = (bitField0_ & ~0x00000100);
        img4_ = getDefaultInstance().getImg4();
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:com.mobile.api.proto.MAddLostOrFound)
    }
    
    static {
      defaultInstance = new MAddLostOrFound(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.mobile.api.proto.MAddLostOrFound)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_mobile_api_proto_MLostAndFoundList_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_mobile_api_proto_MLostAndFoundList_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_mobile_api_proto_MLostAndFound_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_mobile_api_proto_MLostAndFound_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_mobile_api_proto_MAddLostOrFound_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_mobile_api_proto_MAddLostOrFound_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022zsnd_essence.proto\022\024com.mobile.api.pro" +
      "to\"D\n\021MLostAndFoundList\022/\n\002lf\030\001 \003(\0132#.co" +
      "m.mobile.api.proto.MLostAndFound\"\210\001\n\rMLo" +
      "stAndFound\022\n\n\002id\030\001 \001(\t\022\017\n\007address\030\002 \001(\t\022" +
      "\014\n\004desc\030\003 \001(\t\022\016\n\006userid\030\004 \001(\t\022\020\n\010nicknam" +
      "e\030\005 \001(\t\022\017\n\007contact\030\006 \001(\t\022\014\n\004time\030\007 \001(\t\022\013" +
      "\n\003img\030\010 \003(\t\"\225\001\n\017MAddLostOrFound\022\014\n\004type\030" +
      "\001 \001(\005\022\017\n\007address\030\002 \001(\t\022\014\n\004desc\030\003 \001(\t\022\017\n\007" +
      "contact\030\004 \001(\t\022\014\n\004time\030\005 \001(\t\022\014\n\004img1\030\006 \001(" +
      "\014\022\014\n\004img2\030\007 \001(\014\022\014\n\004img3\030\010 \001(\014\022\014\n\004img4\030\t ",
      "\001(\014B\007B\005MLost"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_mobile_api_proto_MLostAndFoundList_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_mobile_api_proto_MLostAndFoundList_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_mobile_api_proto_MLostAndFoundList_descriptor,
              new java.lang.String[] { "Lf", },
              com.mobile.api.proto.MLost.MLostAndFoundList.class,
              com.mobile.api.proto.MLost.MLostAndFoundList.Builder.class);
          internal_static_com_mobile_api_proto_MLostAndFound_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_com_mobile_api_proto_MLostAndFound_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_mobile_api_proto_MLostAndFound_descriptor,
              new java.lang.String[] { "Id", "Address", "Desc", "Userid", "Nickname", "Contact", "Time", "Img", },
              com.mobile.api.proto.MLost.MLostAndFound.class,
              com.mobile.api.proto.MLost.MLostAndFound.Builder.class);
          internal_static_com_mobile_api_proto_MAddLostOrFound_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_com_mobile_api_proto_MAddLostOrFound_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_mobile_api_proto_MAddLostOrFound_descriptor,
              new java.lang.String[] { "Type", "Address", "Desc", "Contact", "Time", "Img1", "Img2", "Img3", "Img4", },
              com.mobile.api.proto.MLost.MAddLostOrFound.class,
              com.mobile.api.proto.MLost.MAddLostOrFound.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
