// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: zsnd_system.proto

package com.mobile.api.proto;

public final class MSystem {
  private MSystem() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface MRetOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // optional int32 code = 1;
    boolean hasCode();
    int getCode();
    
    // optional string msg = 2;
    boolean hasMsg();
    String getMsg();
    
    // optional bytes img = 3;
    boolean hasImg();
    com.google.protobuf.ByteString getImg();
  }
  public static final class MRet extends
      com.google.protobuf.GeneratedMessage
      implements MRetOrBuilder {
    // Use MRet.newBuilder() to construct.
    private MRet(Builder builder) {
      super(builder);
    }
    private MRet(boolean noInit) {}
    
    private static final MRet defaultInstance;
    public static MRet getDefaultInstance() {
      return defaultInstance;
    }
    
    public MRet getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.mobile.api.proto.MSystem.internal_static_com_mobile_api_proto_MRet_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.mobile.api.proto.MSystem.internal_static_com_mobile_api_proto_MRet_fieldAccessorTable;
    }
    
    private int bitField0_;
    // optional int32 code = 1;
    public static final int CODE_FIELD_NUMBER = 1;
    private int code_;
    public boolean hasCode() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public int getCode() {
      return code_;
    }
    
    // optional string msg = 2;
    public static final int MSG_FIELD_NUMBER = 2;
    private java.lang.Object msg_;
    public boolean hasMsg() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getMsg() {
      java.lang.Object ref = msg_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          msg_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getMsgBytes() {
      java.lang.Object ref = msg_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        msg_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional bytes img = 3;
    public static final int IMG_FIELD_NUMBER = 3;
    private com.google.protobuf.ByteString img_;
    public boolean hasImg() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public com.google.protobuf.ByteString getImg() {
      return img_;
    }
    
    private void initFields() {
      code_ = 0;
      msg_ = "";
      img_ = com.google.protobuf.ByteString.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, code_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getMsgBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, img_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, code_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getMsgBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, img_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.mobile.api.proto.MSystem.MRet parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.mobile.api.proto.MSystem.MRet parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.mobile.api.proto.MSystem.MRet parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.mobile.api.proto.MSystem.MRet parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.mobile.api.proto.MSystem.MRet parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.mobile.api.proto.MSystem.MRet parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.mobile.api.proto.MSystem.MRet parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.mobile.api.proto.MSystem.MRet parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.mobile.api.proto.MSystem.MRet parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.mobile.api.proto.MSystem.MRet parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.mobile.api.proto.MSystem.MRet prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.mobile.api.proto.MSystem.MRetOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.mobile.api.proto.MSystem.internal_static_com_mobile_api_proto_MRet_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.mobile.api.proto.MSystem.internal_static_com_mobile_api_proto_MRet_fieldAccessorTable;
      }
      
      // Construct using com.mobile.api.proto.MSystem.MRet.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        code_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        msg_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        img_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.mobile.api.proto.MSystem.MRet.getDescriptor();
      }
      
      public com.mobile.api.proto.MSystem.MRet getDefaultInstanceForType() {
        return com.mobile.api.proto.MSystem.MRet.getDefaultInstance();
      }
      
      public com.mobile.api.proto.MSystem.MRet build() {
        com.mobile.api.proto.MSystem.MRet result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.mobile.api.proto.MSystem.MRet buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.mobile.api.proto.MSystem.MRet result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.mobile.api.proto.MSystem.MRet buildPartial() {
        com.mobile.api.proto.MSystem.MRet result = new com.mobile.api.proto.MSystem.MRet(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.code_ = code_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.msg_ = msg_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.img_ = img_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.mobile.api.proto.MSystem.MRet) {
          return mergeFrom((com.mobile.api.proto.MSystem.MRet)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.mobile.api.proto.MSystem.MRet other) {
        if (other == com.mobile.api.proto.MSystem.MRet.getDefaultInstance()) return this;
        if (other.hasCode()) {
          setCode(other.getCode());
        }
        if (other.hasMsg()) {
          setMsg(other.getMsg());
        }
        if (other.hasImg()) {
          setImg(other.getImg());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              code_ = input.readInt32();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              msg_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              img_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional int32 code = 1;
      private int code_ ;
      public boolean hasCode() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public int getCode() {
        return code_;
      }
      public Builder setCode(int value) {
        bitField0_ |= 0x00000001;
        code_ = value;
        onChanged();
        return this;
      }
      public Builder clearCode() {
        bitField0_ = (bitField0_ & ~0x00000001);
        code_ = 0;
        onChanged();
        return this;
      }
      
      // optional string msg = 2;
      private java.lang.Object msg_ = "";
      public boolean hasMsg() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getMsg() {
        java.lang.Object ref = msg_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          msg_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setMsg(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        msg_ = value;
        onChanged();
        return this;
      }
      public Builder clearMsg() {
        bitField0_ = (bitField0_ & ~0x00000002);
        msg_ = getDefaultInstance().getMsg();
        onChanged();
        return this;
      }
      void setMsg(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000002;
        msg_ = value;
        onChanged();
      }
      
      // optional bytes img = 3;
      private com.google.protobuf.ByteString img_ = com.google.protobuf.ByteString.EMPTY;
      public boolean hasImg() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public com.google.protobuf.ByteString getImg() {
        return img_;
      }
      public Builder setImg(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        img_ = value;
        onChanged();
        return this;
      }
      public Builder clearImg() {
        bitField0_ = (bitField0_ & ~0x00000004);
        img_ = getDefaultInstance().getImg();
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:com.mobile.api.proto.MRet)
    }
    
    static {
      defaultInstance = new MRet(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.mobile.api.proto.MRet)
  }
  
  public interface MImgOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required bytes img = 1;
    boolean hasImg();
    com.google.protobuf.ByteString getImg();
  }
  public static final class MImg extends
      com.google.protobuf.GeneratedMessage
      implements MImgOrBuilder {
    // Use MImg.newBuilder() to construct.
    private MImg(Builder builder) {
      super(builder);
    }
    private MImg(boolean noInit) {}
    
    private static final MImg defaultInstance;
    public static MImg getDefaultInstance() {
      return defaultInstance;
    }
    
    public MImg getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.mobile.api.proto.MSystem.internal_static_com_mobile_api_proto_MImg_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.mobile.api.proto.MSystem.internal_static_com_mobile_api_proto_MImg_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required bytes img = 1;
    public static final int IMG_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString img_;
    public boolean hasImg() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public com.google.protobuf.ByteString getImg() {
      return img_;
    }
    
    private void initFields() {
      img_ = com.google.protobuf.ByteString.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasImg()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, img_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, img_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.mobile.api.proto.MSystem.MImg parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.mobile.api.proto.MSystem.MImg parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.mobile.api.proto.MSystem.MImg parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.mobile.api.proto.MSystem.MImg parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.mobile.api.proto.MSystem.MImg parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.mobile.api.proto.MSystem.MImg parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.mobile.api.proto.MSystem.MImg parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.mobile.api.proto.MSystem.MImg parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.mobile.api.proto.MSystem.MImg parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.mobile.api.proto.MSystem.MImg parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.mobile.api.proto.MSystem.MImg prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.mobile.api.proto.MSystem.MImgOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.mobile.api.proto.MSystem.internal_static_com_mobile_api_proto_MImg_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.mobile.api.proto.MSystem.internal_static_com_mobile_api_proto_MImg_fieldAccessorTable;
      }
      
      // Construct using com.mobile.api.proto.MSystem.MImg.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        img_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.mobile.api.proto.MSystem.MImg.getDescriptor();
      }
      
      public com.mobile.api.proto.MSystem.MImg getDefaultInstanceForType() {
        return com.mobile.api.proto.MSystem.MImg.getDefaultInstance();
      }
      
      public com.mobile.api.proto.MSystem.MImg build() {
        com.mobile.api.proto.MSystem.MImg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.mobile.api.proto.MSystem.MImg buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.mobile.api.proto.MSystem.MImg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.mobile.api.proto.MSystem.MImg buildPartial() {
        com.mobile.api.proto.MSystem.MImg result = new com.mobile.api.proto.MSystem.MImg(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.img_ = img_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.mobile.api.proto.MSystem.MImg) {
          return mergeFrom((com.mobile.api.proto.MSystem.MImg)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.mobile.api.proto.MSystem.MImg other) {
        if (other == com.mobile.api.proto.MSystem.MImg.getDefaultInstance()) return this;
        if (other.hasImg()) {
          setImg(other.getImg());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasImg()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              img_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required bytes img = 1;
      private com.google.protobuf.ByteString img_ = com.google.protobuf.ByteString.EMPTY;
      public boolean hasImg() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public com.google.protobuf.ByteString getImg() {
        return img_;
      }
      public Builder setImg(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        img_ = value;
        onChanged();
        return this;
      }
      public Builder clearImg() {
        bitField0_ = (bitField0_ & ~0x00000001);
        img_ = getDefaultInstance().getImg();
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:com.mobile.api.proto.MImg)
    }
    
    static {
      defaultInstance = new MImg(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.mobile.api.proto.MImg)
  }
  
  public interface MUnreadCountOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // optional int32 essence = 1;
    boolean hasEssence();
    int getEssence();
    
    // optional int32 square = 2;
    boolean hasSquare();
    int getSquare();
    
    // optional int32 standby1 = 3;
    boolean hasStandby1();
    int getStandby1();
    
    // optional int32 standby2 = 4;
    boolean hasStandby2();
    int getStandby2();
  }
  public static final class MUnreadCount extends
      com.google.protobuf.GeneratedMessage
      implements MUnreadCountOrBuilder {
    // Use MUnreadCount.newBuilder() to construct.
    private MUnreadCount(Builder builder) {
      super(builder);
    }
    private MUnreadCount(boolean noInit) {}
    
    private static final MUnreadCount defaultInstance;
    public static MUnreadCount getDefaultInstance() {
      return defaultInstance;
    }
    
    public MUnreadCount getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.mobile.api.proto.MSystem.internal_static_com_mobile_api_proto_MUnreadCount_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.mobile.api.proto.MSystem.internal_static_com_mobile_api_proto_MUnreadCount_fieldAccessorTable;
    }
    
    private int bitField0_;
    // optional int32 essence = 1;
    public static final int ESSENCE_FIELD_NUMBER = 1;
    private int essence_;
    public boolean hasEssence() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public int getEssence() {
      return essence_;
    }
    
    // optional int32 square = 2;
    public static final int SQUARE_FIELD_NUMBER = 2;
    private int square_;
    public boolean hasSquare() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public int getSquare() {
      return square_;
    }
    
    // optional int32 standby1 = 3;
    public static final int STANDBY1_FIELD_NUMBER = 3;
    private int standby1_;
    public boolean hasStandby1() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public int getStandby1() {
      return standby1_;
    }
    
    // optional int32 standby2 = 4;
    public static final int STANDBY2_FIELD_NUMBER = 4;
    private int standby2_;
    public boolean hasStandby2() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public int getStandby2() {
      return standby2_;
    }
    
    private void initFields() {
      essence_ = 0;
      square_ = 0;
      standby1_ = 0;
      standby2_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, essence_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, square_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, standby1_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(4, standby2_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, essence_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, square_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, standby1_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, standby2_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.mobile.api.proto.MSystem.MUnreadCount parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.mobile.api.proto.MSystem.MUnreadCount parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.mobile.api.proto.MSystem.MUnreadCount parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.mobile.api.proto.MSystem.MUnreadCount parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.mobile.api.proto.MSystem.MUnreadCount parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.mobile.api.proto.MSystem.MUnreadCount parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.mobile.api.proto.MSystem.MUnreadCount parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.mobile.api.proto.MSystem.MUnreadCount parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.mobile.api.proto.MSystem.MUnreadCount parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.mobile.api.proto.MSystem.MUnreadCount parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.mobile.api.proto.MSystem.MUnreadCount prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.mobile.api.proto.MSystem.MUnreadCountOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.mobile.api.proto.MSystem.internal_static_com_mobile_api_proto_MUnreadCount_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.mobile.api.proto.MSystem.internal_static_com_mobile_api_proto_MUnreadCount_fieldAccessorTable;
      }
      
      // Construct using com.mobile.api.proto.MSystem.MUnreadCount.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        essence_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        square_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        standby1_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        standby2_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.mobile.api.proto.MSystem.MUnreadCount.getDescriptor();
      }
      
      public com.mobile.api.proto.MSystem.MUnreadCount getDefaultInstanceForType() {
        return com.mobile.api.proto.MSystem.MUnreadCount.getDefaultInstance();
      }
      
      public com.mobile.api.proto.MSystem.MUnreadCount build() {
        com.mobile.api.proto.MSystem.MUnreadCount result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.mobile.api.proto.MSystem.MUnreadCount buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.mobile.api.proto.MSystem.MUnreadCount result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.mobile.api.proto.MSystem.MUnreadCount buildPartial() {
        com.mobile.api.proto.MSystem.MUnreadCount result = new com.mobile.api.proto.MSystem.MUnreadCount(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.essence_ = essence_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.square_ = square_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.standby1_ = standby1_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.standby2_ = standby2_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.mobile.api.proto.MSystem.MUnreadCount) {
          return mergeFrom((com.mobile.api.proto.MSystem.MUnreadCount)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.mobile.api.proto.MSystem.MUnreadCount other) {
        if (other == com.mobile.api.proto.MSystem.MUnreadCount.getDefaultInstance()) return this;
        if (other.hasEssence()) {
          setEssence(other.getEssence());
        }
        if (other.hasSquare()) {
          setSquare(other.getSquare());
        }
        if (other.hasStandby1()) {
          setStandby1(other.getStandby1());
        }
        if (other.hasStandby2()) {
          setStandby2(other.getStandby2());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              essence_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              square_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              standby1_ = input.readInt32();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              standby2_ = input.readInt32();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional int32 essence = 1;
      private int essence_ ;
      public boolean hasEssence() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public int getEssence() {
        return essence_;
      }
      public Builder setEssence(int value) {
        bitField0_ |= 0x00000001;
        essence_ = value;
        onChanged();
        return this;
      }
      public Builder clearEssence() {
        bitField0_ = (bitField0_ & ~0x00000001);
        essence_ = 0;
        onChanged();
        return this;
      }
      
      // optional int32 square = 2;
      private int square_ ;
      public boolean hasSquare() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public int getSquare() {
        return square_;
      }
      public Builder setSquare(int value) {
        bitField0_ |= 0x00000002;
        square_ = value;
        onChanged();
        return this;
      }
      public Builder clearSquare() {
        bitField0_ = (bitField0_ & ~0x00000002);
        square_ = 0;
        onChanged();
        return this;
      }
      
      // optional int32 standby1 = 3;
      private int standby1_ ;
      public boolean hasStandby1() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public int getStandby1() {
        return standby1_;
      }
      public Builder setStandby1(int value) {
        bitField0_ |= 0x00000004;
        standby1_ = value;
        onChanged();
        return this;
      }
      public Builder clearStandby1() {
        bitField0_ = (bitField0_ & ~0x00000004);
        standby1_ = 0;
        onChanged();
        return this;
      }
      
      // optional int32 standby2 = 4;
      private int standby2_ ;
      public boolean hasStandby2() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public int getStandby2() {
        return standby2_;
      }
      public Builder setStandby2(int value) {
        bitField0_ |= 0x00000008;
        standby2_ = value;
        onChanged();
        return this;
      }
      public Builder clearStandby2() {
        bitField0_ = (bitField0_ & ~0x00000008);
        standby2_ = 0;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:com.mobile.api.proto.MUnreadCount)
    }
    
    static {
      defaultInstance = new MUnreadCount(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.mobile.api.proto.MUnreadCount)
  }
  
  public interface MRecomendKeysOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // repeated string key = 1;
    java.util.List<String> getKeyList();
    int getKeyCount();
    String getKey(int index);
  }
  public static final class MRecomendKeys extends
      com.google.protobuf.GeneratedMessage
      implements MRecomendKeysOrBuilder {
    // Use MRecomendKeys.newBuilder() to construct.
    private MRecomendKeys(Builder builder) {
      super(builder);
    }
    private MRecomendKeys(boolean noInit) {}
    
    private static final MRecomendKeys defaultInstance;
    public static MRecomendKeys getDefaultInstance() {
      return defaultInstance;
    }
    
    public MRecomendKeys getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.mobile.api.proto.MSystem.internal_static_com_mobile_api_proto_MRecomendKeys_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.mobile.api.proto.MSystem.internal_static_com_mobile_api_proto_MRecomendKeys_fieldAccessorTable;
    }
    
    // repeated string key = 1;
    public static final int KEY_FIELD_NUMBER = 1;
    private com.google.protobuf.LazyStringList key_;
    public java.util.List<String>
        getKeyList() {
      return key_;
    }
    public int getKeyCount() {
      return key_.size();
    }
    public String getKey(int index) {
      return key_.get(index);
    }
    
    private void initFields() {
      key_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < key_.size(); i++) {
        output.writeBytes(1, key_.getByteString(i));
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      {
        int dataSize = 0;
        for (int i = 0; i < key_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(key_.getByteString(i));
        }
        size += dataSize;
        size += 1 * getKeyList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.mobile.api.proto.MSystem.MRecomendKeys parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.mobile.api.proto.MSystem.MRecomendKeys parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.mobile.api.proto.MSystem.MRecomendKeys parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.mobile.api.proto.MSystem.MRecomendKeys parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.mobile.api.proto.MSystem.MRecomendKeys parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.mobile.api.proto.MSystem.MRecomendKeys parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.mobile.api.proto.MSystem.MRecomendKeys parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.mobile.api.proto.MSystem.MRecomendKeys parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.mobile.api.proto.MSystem.MRecomendKeys parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.mobile.api.proto.MSystem.MRecomendKeys parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.mobile.api.proto.MSystem.MRecomendKeys prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.mobile.api.proto.MSystem.MRecomendKeysOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.mobile.api.proto.MSystem.internal_static_com_mobile_api_proto_MRecomendKeys_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.mobile.api.proto.MSystem.internal_static_com_mobile_api_proto_MRecomendKeys_fieldAccessorTable;
      }
      
      // Construct using com.mobile.api.proto.MSystem.MRecomendKeys.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        key_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.mobile.api.proto.MSystem.MRecomendKeys.getDescriptor();
      }
      
      public com.mobile.api.proto.MSystem.MRecomendKeys getDefaultInstanceForType() {
        return com.mobile.api.proto.MSystem.MRecomendKeys.getDefaultInstance();
      }
      
      public com.mobile.api.proto.MSystem.MRecomendKeys build() {
        com.mobile.api.proto.MSystem.MRecomendKeys result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.mobile.api.proto.MSystem.MRecomendKeys buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.mobile.api.proto.MSystem.MRecomendKeys result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.mobile.api.proto.MSystem.MRecomendKeys buildPartial() {
        com.mobile.api.proto.MSystem.MRecomendKeys result = new com.mobile.api.proto.MSystem.MRecomendKeys(this);
        int from_bitField0_ = bitField0_;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          key_ = new com.google.protobuf.UnmodifiableLazyStringList(
              key_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.key_ = key_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.mobile.api.proto.MSystem.MRecomendKeys) {
          return mergeFrom((com.mobile.api.proto.MSystem.MRecomendKeys)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.mobile.api.proto.MSystem.MRecomendKeys other) {
        if (other == com.mobile.api.proto.MSystem.MRecomendKeys.getDefaultInstance()) return this;
        if (!other.key_.isEmpty()) {
          if (key_.isEmpty()) {
            key_ = other.key_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureKeyIsMutable();
            key_.addAll(other.key_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              ensureKeyIsMutable();
              key_.add(input.readBytes());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // repeated string key = 1;
      private com.google.protobuf.LazyStringList key_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureKeyIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          key_ = new com.google.protobuf.LazyStringArrayList(key_);
          bitField0_ |= 0x00000001;
         }
      }
      public java.util.List<String>
          getKeyList() {
        return java.util.Collections.unmodifiableList(key_);
      }
      public int getKeyCount() {
        return key_.size();
      }
      public String getKey(int index) {
        return key_.get(index);
      }
      public Builder setKey(
          int index, String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureKeyIsMutable();
        key_.set(index, value);
        onChanged();
        return this;
      }
      public Builder addKey(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureKeyIsMutable();
        key_.add(value);
        onChanged();
        return this;
      }
      public Builder addAllKey(
          java.lang.Iterable<String> values) {
        ensureKeyIsMutable();
        super.addAll(values, key_);
        onChanged();
        return this;
      }
      public Builder clearKey() {
        key_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      void addKey(com.google.protobuf.ByteString value) {
        ensureKeyIsMutable();
        key_.add(value);
        onChanged();
      }
      
      // @@protoc_insertion_point(builder_scope:com.mobile.api.proto.MRecomendKeys)
    }
    
    static {
      defaultInstance = new MRecomendKeys(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.mobile.api.proto.MRecomendKeys)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_mobile_api_proto_MRet_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_mobile_api_proto_MRet_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_mobile_api_proto_MImg_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_mobile_api_proto_MImg_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_mobile_api_proto_MUnreadCount_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_mobile_api_proto_MUnreadCount_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_mobile_api_proto_MRecomendKeys_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_mobile_api_proto_MRecomendKeys_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021zsnd_system.proto\022\024com.mobile.api.prot" +
      "o\".\n\004MRet\022\014\n\004code\030\001 \001(\005\022\013\n\003msg\030\002 \001(\t\022\013\n\003" +
      "img\030\003 \001(\014\"\023\n\004MImg\022\013\n\003img\030\001 \002(\014\"S\n\014MUnrea" +
      "dCount\022\017\n\007essence\030\001 \001(\005\022\016\n\006square\030\002 \001(\005\022" +
      "\020\n\010standby1\030\003 \001(\005\022\020\n\010standby2\030\004 \001(\005\"\034\n\rM" +
      "RecomendKeys\022\013\n\003key\030\001 \003(\tB\tB\007MSystem"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_mobile_api_proto_MRet_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_mobile_api_proto_MRet_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_mobile_api_proto_MRet_descriptor,
              new java.lang.String[] { "Code", "Msg", "Img", },
              com.mobile.api.proto.MSystem.MRet.class,
              com.mobile.api.proto.MSystem.MRet.Builder.class);
          internal_static_com_mobile_api_proto_MImg_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_com_mobile_api_proto_MImg_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_mobile_api_proto_MImg_descriptor,
              new java.lang.String[] { "Img", },
              com.mobile.api.proto.MSystem.MImg.class,
              com.mobile.api.proto.MSystem.MImg.Builder.class);
          internal_static_com_mobile_api_proto_MUnreadCount_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_com_mobile_api_proto_MUnreadCount_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_mobile_api_proto_MUnreadCount_descriptor,
              new java.lang.String[] { "Essence", "Square", "Standby1", "Standby2", },
              com.mobile.api.proto.MSystem.MUnreadCount.class,
              com.mobile.api.proto.MSystem.MUnreadCount.Builder.class);
          internal_static_com_mobile_api_proto_MRecomendKeys_descriptor =
            getDescriptor().getMessageTypes().get(3);
          internal_static_com_mobile_api_proto_MRecomendKeys_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_mobile_api_proto_MRecomendKeys_descriptor,
              new java.lang.String[] { "Key", },
              com.mobile.api.proto.MSystem.MRecomendKeys.class,
              com.mobile.api.proto.MSystem.MRecomendKeys.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
